### ISSUE TITLE
Is it possible to use kosmtik with tm2 project (from Mapbox Studio Classic)?

### ISSUE THREAD

**Issue by petervojtek** [kosmtik/kosmtik#103]
Hello,

I am trying to display a project created in Mapbox Studio Classic in Kosmtik. I am not sure if it is possible at all or if some kind of conversion must be undertaken. 
Here is outcome of my attempt:

```
node index.js serve ../cyklomapa-v6.tm2/project.yml
[Core] No usable config file found in /home/peter/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading project from ../cyklomapa-v6.tm2/project.yml

TypeError: Cannot call method 'indexOf' of null
    at BaseLoader.normalizeSource (/home/peter/repos/kosmtik/src/back/loader/Base.js:47:36)
    at Array.map (native)
    at BaseLoader.postprocess (/home/peter/repos/kosmtik/src/back/loader/Base.js:24:43)
    at BaseLoader.load (/home/peter/repos/kosmtik/src/back/loader/Base.js:75:10)
    at Project.load (/home/peter/repos/kosmtik/src/back/Project.js:37:23)
    at new ProjectServer (/home/peter/repos/kosmtik/src/back/ProjectServer.js:30:18)
    at PreviewServer.registerProject (/home/peter/repos/kosmtik/src/back/PreviewServer.js:51:33)
    at PreviewServer.listen (/home/peter/repos/kosmtik/src/back/PreviewServer.js:42:14)
    at EventEmitter.emit (events.js:92:17)
    at Config.parseOptions (/home/peter/repos/kosmtik/src/Config.js:134:10)

```

**Comment by skorasaurus** [comment]
Not yet, Discussion and code for this is at https://github.com/kosmtik/kosmtik/issues/8

**Comment by petervojtek** [comment]
thanks for quick reply.

**Comment by yohanboniface** [comment]
Just a bit more details: vector tiles based project are supported BUT not vector tiles providers needing authentication.
