### ISSUE TITLE
problem with plugins --available

### ISSUE THREAD

**Issue by denics** [kosmtik/kosmtik#105]
Hi all, 
I just did a new, fresh installation (macos) and it seems that there is a problem with the available function:

```
denix@deniss-mac-pro:/git/kosmtik(master) $ node index.js plugins --available
[Core] Loading config from /Users/denix/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Unable to load plugin kosmtik-deploy MODULE_NOT_FOUND
[Core] Unable to load plugin kosmtik-fetch-remote MODULE_NOT_FOUND
Loading available plugins…
/git/kosmtik/node_modules/npm/lib/cache/update-index.js:61
            var t = +data._updated || 0
                         ^

TypeError: Cannot read property '_updated' of undefined
    at /git/kosmtik/node_modules/npm/lib/cache/update-index.js:61:26
    at /git/kosmtik/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by yohanboniface** [comment]
Which node version?

**Comment by denics** [comment]
```
$ node -v
v5.5.0
```

**Comment by denizdogan** [comment]
I don't think it's a problem specific to this project, because we have the same problem at jnordberg/wintersmith#314

**Comment by yohanboniface** [comment]
Yes, let's track this on #149
