### ISSUE TITLE
Broken with latest Mapnik

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#107]
```
[httpserver] /repo/tile/9/88/170.png?t=1455001627333 500
Trace
    at ProjectServer.raise (/home/pnorman/osm/kosmtik-3/src/back/ProjectServer.js:239:13)
    at /home/pnorman/osm/kosmtik-3/src/back/ProjectServer.js:73:34
    at /home/pnorman/osm/kosmtik-3/src/back/MetatileBasedTile.js:44:45
    at Object.oncomplete (fs.js:107:15)
Invalid index file
```

A `git clean -xfd` and new `npm install` did not fix this. Version 4c6fa1c

**Comment by yohanboniface** [comment]
Can you paste "npm list" output? Also, which node version?

(How much I regret the NodeJS choice, amigo! That's unmaintainable unless you have a team of ten people to continuously checks all the conflicts with the thousands of dependencies and dependencies of dependencies that get upgraded on and on without any consideration for retrocompatibility over time…)

**Comment by pnorman** [comment]
`npm list` stdout

```
kosmtik@0.0.13 /home/pnorman/osm/kosmtik-3
├─┬ carto@0.15.3
│ ├── mapnik-reference@8.5.2
│ ├─┬ optimist@0.6.1
│ │ ├── minimist@0.0.10
│ │ └── wordwrap@0.0.3
│ └── underscore@1.6.0
├── generic-pool@2.4.0
├─┬ js-yaml@3.5.2
│ ├─┬ argparse@1.0.6
│ │ └── sprintf-js@1.0.3
│ └── esprima@2.7.2
├── json-localizer@0.0.3
├── leaflet@1.0.0-beta.2
├── leaflet-formbuilder@0.2.1
├── leaflet-hash@0.2.1
├─┬ mapnik@3.4.16
│ ├── mapnik-vector-tile@0.14.3
│ ├── nan@2.2.0
│ └─┬ node-pre-gyp@0.6.19
│   ├─┬ mkdirp@0.5.1
│   │ └── minimist@0.0.8
│   ├─┬ nopt@3.0.6
│   │ └── abbrev@1.0.7
│   ├─┬ npmlog@2.0.0
│   │ ├── ansi@0.3.0
│   │ ├─┬ are-we-there-yet@1.0.5
│   │ │ ├── delegates@0.1.0
│   │ │ └─┬ readable-stream@2.0.5
│   │ │   ├── core-util-is@1.0.2
│   │ │   ├── inherits@2.0.1
│   │ │   ├── isarray@0.0.1
│   │ │   ├── process-nextick-args@1.0.6
│   │ │   ├── string_decoder@0.10.31
│   │ │   └── util-deprecate@1.0.2
│   │ └─┬ gauge@1.2.2
│   │   ├── has-unicode@1.0.1
│   │   ├─┬ lodash.pad@3.1.1
│   │   │ ├── lodash._basetostring@3.0.1
│   │   │ └─┬ lodash._createpadding@3.6.1
│   │   │   └── lodash.repeat@3.0.1
│   │   ├─┬ lodash.padleft@3.1.1
│   │   │ ├── lodash._basetostring@3.0.1
│   │   │ └─┬ lodash._createpadding@3.6.1
│   │   │   └── lodash.repeat@3.0.1
│   │   └─┬ lodash.padright@3.1.1
│   │     ├── lodash._basetostring@3.0.1
│   │     └─┬ lodash._createpadding@3.6.1
│   │       └── lodash.repeat@3.0.1
│   ├─┬ rc@1.1.6
│   │ ├── deep-extend@0.4.0
│   │ ├── ini@1.3.4
│   │ ├── minimist@1.2.0
│   │ └── strip-json-comments@1.0.4
│   ├─┬ request@2.67.0
│   │ ├── aws-sign2@0.6.0
│   │ ├─┬ bl@1.0.0
│   │ │ └─┬ readable-stream@2.0.5
│   │ │   ├── core-util-is@1.0.2
│   │ │   ├── inherits@2.0.1
│   │ │   ├── isarray@0.0.1
│   │ │   ├── process-nextick-args@1.0.6
│   │ │   ├── string_decoder@0.10.31
│   │ │   └── util-deprecate@1.0.2
│   │ ├── caseless@0.11.0
│   │ ├─┬ combined-stream@1.0.5
│   │ │ └── delayed-stream@1.0.0
│   │ ├── extend@3.0.0
│   │ ├── forever-agent@0.6.1
│   │ ├─┬ form-data@1.0.0-rc3
│   │ │ └── async@1.5.1
│   │ ├─┬ har-validator@2.0.3
│   │ │ ├─┬ chalk@1.1.1
│   │ │ │ ├── ansi-styles@2.1.0
│   │ │ │ ├── escape-string-regexp@1.0.4
│   │ │ │ ├─┬ has-ansi@2.0.0
│   │ │ │ │ └── ansi-regex@2.0.0
│   │ │ │ ├─┬ strip-ansi@3.0.0
│   │ │ │ │ └── ansi-regex@2.0.0
│   │ │ │ └── supports-color@2.0.0
│   │ │ ├─┬ commander@2.9.0
│   │ │ │ └── graceful-readlink@1.0.1
│   │ │ ├─┬ is-my-json-valid@2.12.3
│   │ │ │ ├── generate-function@2.0.0
│   │ │ │ ├─┬ generate-object-property@1.2.0
│   │ │ │ │ └── is-property@1.0.2
│   │ │ │ ├── jsonpointer@2.0.0
│   │ │ │ └── xtend@4.0.1
│   │ │ └─┬ pinkie-promise@2.0.0
│   │ │   └── pinkie@2.0.1
│   │ ├─┬ hawk@3.1.2
│   │ │ ├── boom@2.10.1
│   │ │ ├── cryptiles@2.0.5
│   │ │ ├── hoek@2.16.3
│   │ │ └── sntp@1.0.9
│   │ ├─┬ http-signature@1.1.0
│   │ │ ├── assert-plus@0.1.5
│   │ │ ├─┬ jsprim@1.2.2
│   │ │ │ ├── extsprintf@1.0.2
│   │ │ │ ├── json-schema@0.2.2
│   │ │ │ └── verror@1.3.6
│   │ │ └─┬ sshpk@1.7.2
│   │ │   ├── asn1@0.2.3
│   │ │   ├── assert-plus@0.2.0
│   │ │   ├─┬ dashdash@1.11.0
│   │ │   │ └── assert-plus@0.1.5
│   │ │   ├── ecc-jsbn@0.1.1
│   │ │   ├── jodid25519@1.0.2
│   │ │   ├── jsbn@0.1.0
│   │ │   └── tweetnacl@0.13.2
│   │ ├── is-typedarray@1.0.0
│   │ ├── isstream@0.1.2
│   │ ├── json-stringify-safe@5.0.1
│   │ ├─┬ mime-types@2.1.9
│   │ │ └── mime-db@1.21.0
│   │ ├── node-uuid@1.4.7
│   │ ├── oauth-sign@0.8.0
│   │ ├── qs@5.2.0
│   │ ├── stringstream@0.0.5
│   │ ├── tough-cookie@2.2.1
│   │ └── tunnel-agent@0.4.2
│   ├─┬ rimraf@2.5.0
│   │ └─┬ glob@6.0.3
│   │   ├─┬ inflight@1.0.4
│   │   │ └── wrappy@1.0.1
│   │   ├── inherits@2.0.1
│   │   ├─┬ minimatch@3.0.0
│   │   │ └─┬ brace-expansion@1.1.2
│   │   │   ├── balanced-match@0.3.0
│   │   │   └── concat-map@0.0.1
│   │   ├─┬ once@1.3.3
│   │   │ └── wrappy@1.0.1
│   │   └── path-is-absolute@1.0.0
│   ├── semver@5.1.0
│   ├─┬ tar@2.2.1
│   │ ├── block-stream@0.0.8
│   │ ├─┬ fstream@1.0.8
│   │ │ └── graceful-fs@4.1.2
│   │ └── inherits@2.0.1
│   └─┬ tar-pack@3.1.2
│     ├── debug@0.7.4
│     ├─┬ fstream@1.0.8
│     │ ├── graceful-fs@4.1.2
│     │ └── inherits@2.0.1
│     ├─┬ fstream-ignore@1.0.3
│     │ ├── inherits@2.0.1
│     │ └─┬ minimatch@3.0.0
│     │   └─┬ brace-expansion@1.1.2
│     │     ├── balanced-match@0.3.0
│     │     └── concat-map@0.0.1
│     ├── once@1.1.1
│     ├─┬ readable-stream@2.0.5
│     │ ├── core-util-is@1.0.2
│     │ ├── inherits@2.0.1
│     │ ├── isarray@0.0.1
│     │ ├── process-nextick-args@1.0.6
│     │ ├── string_decoder@0.10.31
│     │ └── util-deprecate@1.0.2
│     ├─┬ rimraf@2.4.5
│     │ └─┬ glob@6.0.3
│     │   ├─┬ inflight@1.0.4
│     │   │ └── wrappy@1.0.1
│     │   ├── inherits@2.0.1
│     │   ├─┬ minimatch@3.0.0
│     │   │ └─┬ brace-expansion@1.1.2
│     │   │   ├── balanced-match@0.3.0
│     │   │   └── concat-map@0.0.1
│     │   ├─┬ once@1.3.3
│     │   │ └── wrappy@1.0.1
│     │   └── path-is-absolute@1.0.0
│     └── uid-number@0.0.3
├─┬ mocha@2.4.5
│ ├── commander@2.3.0
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── diff@1.4.0
│ ├── escape-string-regexp@1.0.2
│ ├─┬ glob@3.2.3
│ │ ├── graceful-fs@2.0.3
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@0.2.14
│ │   ├── lru-cache@2.7.3
│ │   └── sigmund@1.0.1
│ ├── growl@1.8.1
│ ├─┬ jade@0.26.3
│ │ ├── commander@0.6.1
│ │ └── mkdirp@0.3.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └── supports-color@1.2.0
├─┬ nomnom@1.8.1
│ ├─┬ chalk@0.4.0
│ │ ├── ansi-styles@1.0.0
│ │ ├── has-color@0.1.7
│ │ └── strip-ansi@0.1.1
│ └── underscore@1.6.0
├─┬ npm@3.7.1
│ ├── abbrev@1.0.7
│ ├── ansi-regex@2.0.0
│ ├── ansicolors@0.3.2
│ ├── ansistyles@0.1.3
│ ├── aproba@1.0.1
│ ├── archy@1.0.0
│ ├── async-some@1.0.2
│ ├── chownr@1.0.1
│ ├─┬ cmd-shim@2.0.1
│ │ └── graceful-fs@3.0.8
│ ├─┬ columnify@1.5.4
│ │ └─┬ wcwidth@1.0.0
│ │   └─┬ defaults@1.0.3
│ │     └── clone@1.0.2
│ ├─┬ config-chain@1.1.10
│ │ └── proto-list@1.2.4
│ ├── debuglog@1.0.1
│ ├─┬ dezalgo@1.0.3
│ │ └── asap@2.0.3
│ ├── editor@1.0.0
│ ├── fs-vacuum@1.2.7
│ ├── fs-write-stream-atomic@1.0.8
│ ├── fstream@1.0.8
│ ├─┬ fstream-npm@1.0.7
│ │ └─┬ fstream-ignore@1.0.3
│ │   └─┬ minimatch@3.0.0
│ │     └─┬ brace-expansion@1.1.2
│ │       ├── balanced-match@0.3.0
│ │       └── concat-map@0.0.1
│ ├─┬ glob@6.0.4
│ │ ├─┬ minimatch@3.0.0
│ │ │ └─┬ brace-expansion@1.1.2
│ │ │   ├── balanced-match@0.3.0
│ │ │   └── concat-map@0.0.1
│ │ └── path-is-absolute@1.0.0
│ ├── graceful-fs@4.1.2
│ ├── has-unicode@2.0.0
│ ├── hosted-git-info@2.1.4
│ ├── iferr@0.1.5
│ ├── imurmurhash@0.1.4
│ ├── inflight@1.0.4
│ ├── inherits@2.0.1
│ ├── ini@1.3.4
│ ├─┬ init-package-json@1.9.3
│ │ └── promzard@0.3.0
│ ├── lockfile@1.0.1
│ ├── lodash._baseindexof@3.1.0
│ ├── lodash._baseuniq@3.0.3 extraneous
│ ├── lodash._bindcallback@3.0.1 extraneous
│ ├── lodash._cacheindexof@3.0.2
│ ├── lodash._createcache@3.1.2
│ ├── lodash._getnative@3.9.1
│ ├─┬ lodash.clonedeep@4.0.2
│ │ ├── lodash._arrayeach@3.0.0
│ │ ├── lodash._basefor@3.0.3
│ │ └─┬ lodash._stack@4.0.1
│ │   └── lodash._mapcache@4.0.0
│ ├── lodash.isarguments@3.0.5
│ ├── lodash.isarray@4.0.0
│ ├── lodash.keys@4.0.0
│ ├── lodash.restparam@3.6.1 extraneous
│ ├─┬ lodash.union@4.0.1
│ │ ├── lodash._arrayincludes@4.0.0
│ │ ├── lodash._arrayincludeswith@4.0.0
│ │ ├── lodash._baseflatten@4.0.0
│ │ ├── lodash._cachehas@4.0.0
│ │ ├─┬ lodash._setcache@4.0.1
│ │ │ └── lodash._mapcache@4.0.0
│ │ └── lodash.rest@4.0.0
│ ├─┬ lodash.uniq@4.0.1
│ │ ├── lodash._arrayincludes@4.0.0
│ │ ├── lodash._arrayincludeswith@4.0.0
│ │ ├── lodash._cachehas@4.0.0
│ │ └─┬ lodash._setcache@4.0.1
│ │   └── lodash._mapcache@4.0.0
│ ├─┬ lodash.without@4.0.1
│ │ ├── lodash._arrayincludes@4.0.0
│ │ ├── lodash._arrayincludeswith@4.0.0
│ │ ├── lodash._arraymap@3.0.0
│ │ ├── lodash._cachehas@4.0.0
│ │ ├─┬ lodash._setcache@4.0.1
│ │ │ └── lodash._mapcache@4.0.0
│ │ └── lodash.rest@4.0.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ node-gyp@3.2.1
│ │ ├─┬ glob@4.5.3
│ │ │ └─┬ minimatch@2.0.10
│ │ │   └─┬ brace-expansion@1.1.2
│ │ │     ├── balanced-match@0.3.0
│ │ │     └── concat-map@0.0.1
│ │ ├─┬ minimatch@1.0.0
│ │ │ ├── lru-cache@2.7.3
│ │ │ └── sigmund@1.0.1
│ │ ├─┬ npmlog@1.2.1
│ │ │ ├── ansi@0.3.1
│ │ │ ├─┬ are-we-there-yet@1.0.5
│ │ │ │ └── delegates@0.1.0
│ │ │ └─┬ gauge@1.2.4
│ │ │   ├─┬ lodash.pad@3.2.0
│ │ │   │ └── lodash.repeat@3.1.0
│ │ │   ├─┬ lodash.padleft@3.1.1
│ │ │   │ ├── lodash._basetostring@3.0.1
│ │ │   │ └─┬ lodash._createpadding@3.6.1
│ │ │   │   └── lodash.repeat@3.1.0
│ │ │   └─┬ lodash.padright@3.1.1
│ │ │     ├── lodash._basetostring@3.0.1
│ │ │     └─┬ lodash._createpadding@3.6.1
│ │ │       └── lodash.repeat@3.1.0
│ │ └─┬ path-array@1.0.1
│ │   └─┬ array-index@1.0.0
│ │     ├─┬ debug@2.2.0
│ │     │ └── ms@0.7.1
│ │     └─┬ es6-symbol@3.0.2
│ │       ├── d@0.1.1
│ │       └─┬ es5-ext@0.10.11
│ │         └── es6-iterator@2.0.0
│ ├── nopt@3.0.6
│ ├── normalize-git-url@3.0.1
│ ├─┬ normalize-package-data@2.3.5
│ │ └─┬ is-builtin-module@1.0.0
│ │   └── builtin-modules@1.1.1
│ ├── npm-cache-filename@1.0.2
│ ├── npm-install-checks@3.0.0
│ ├── npm-package-arg@4.1.0
│ ├─┬ npm-registry-client@7.0.9
│ │ ├─┬ concat-stream@1.5.1
│ │ │ └── typedarray@0.0.6
│ │ └── retry@0.8.0
│ ├── npm-user-validate@0.1.2
│ ├─┬ npmlog@2.0.2
│ │ ├── ansi@0.3.1
│ │ ├─┬ are-we-there-yet@1.0.6
│ │ │ └── delegates@1.0.0
│ │ └─┬ gauge@1.2.5
│ │   ├─┬ lodash.pad@3.2.1
│ │   │ └── lodash.repeat@3.1.1
│ │   ├─┬ lodash.padleft@3.1.1
│ │   │ ├── lodash._basetostring@3.0.1
│ │   │ └─┬ lodash._createpadding@3.6.1
│ │   │   └── lodash.repeat@3.1.1
│ │   └─┬ lodash.padright@3.1.1
│ │     ├── lodash._basetostring@3.0.1
│ │     └─┬ lodash._createpadding@3.6.1
│ │       └── lodash.repeat@3.1.1
│ ├── once@1.3.3
│ ├── opener@1.4.1
│ ├─┬ osenv@0.1.3
│ │ ├── os-homedir@1.0.1
│ │ └── os-tmpdir@1.0.1
│ ├── path-is-inside@1.0.1
│ ├─┬ read@1.0.7
│ │ └── mute-stream@0.0.5
│ ├── read-cmd-shim@1.0.1
│ ├─┬ read-installed@4.0.3
│ │ └── util-extend@1.0.3
│ ├─┬ read-package-json@2.0.3
│ │ └─┬ json-parse-helpfulerror@1.0.3
│ │   └── jju@1.2.1
│ ├── read-package-tree@5.1.2
│ ├─┬ readable-stream@2.0.5
│ │ ├── core-util-is@1.0.2
│ │ ├── isarray@0.0.1
│ │ ├── process-nextick-args@1.0.6
│ │ ├── string_decoder@0.10.31
│ │ └── util-deprecate@1.0.2
│ ├── readdir-scoped-modules@1.0.2
│ ├── realize-package-specifier@3.0.1
│ ├─┬ request@2.69.0
│ │ ├── aws-sign2@0.6.0
│ │ ├─┬ aws4@1.2.1
│ │ │ └── lru-cache@2.7.3
│ │ ├── bl@1.0.1
│ │ ├── caseless@0.11.0
│ │ ├─┬ combined-stream@1.0.5
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.0
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@1.0.0-rc3
│ │ │ └── async@1.5.2
│ │ ├─┬ har-validator@2.0.6
│ │ │ ├─┬ chalk@1.1.1
│ │ │ │ ├── ansi-styles@2.1.0
│ │ │ │ ├── escape-string-regexp@1.0.4
│ │ │ │ ├── has-ansi@2.0.0
│ │ │ │ └── supports-color@2.0.0
│ │ │ ├─┬ commander@2.9.0
│ │ │ │ └── graceful-readlink@1.0.1
│ │ │ ├─┬ is-my-json-valid@2.12.4
│ │ │ │ ├── generate-function@2.0.0
│ │ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ │ └── is-property@1.0.2
│ │ │ │ ├── jsonpointer@2.0.0
│ │ │ │ └── xtend@4.0.1
│ │ │ └─┬ pinkie-promise@2.0.0
│ │ │   └── pinkie@2.0.1
│ │ ├─┬ hawk@3.1.3
│ │ │ ├── boom@2.10.1
│ │ │ ├── cryptiles@2.0.5
│ │ │ ├── hoek@2.16.3
│ │ │ └── sntp@1.0.9
│ │ ├─┬ http-signature@1.1.1
│ │ │ ├── assert-plus@0.2.0
│ │ │ ├─┬ jsprim@1.2.2
│ │ │ │ ├── extsprintf@1.0.2
│ │ │ │ ├── json-schema@0.2.2
│ │ │ │ └── verror@1.3.6
│ │ │ └─┬ sshpk@1.7.3
│ │ │   ├── asn1@0.2.3
│ │ │   ├── dashdash@1.12.2
│ │ │   ├── ecc-jsbn@0.1.1
│ │ │   ├── jodid25519@1.0.2
│ │ │   ├── jsbn@0.1.0
│ │ │   └── tweetnacl@0.13.3
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.1.9
│ │ │ └── mime-db@1.21.0
│ │ ├── node-uuid@1.4.7
│ │ ├── oauth-sign@0.8.0
│ │ ├── qs@6.0.2
│ │ ├── stringstream@0.0.5
│ │ ├── tough-cookie@2.2.1
│ │ └── tunnel-agent@0.4.2
│ ├── retry@0.9.0
│ ├── rimraf@2.5.1
│ ├── semver@5.1.0
│ ├── sha@2.0.1
│ ├── slide@1.1.6
│ ├── sorted-object@1.0.0
│ ├── strip-ansi@3.0.0
│ ├─┬ tar@2.2.1
│ │ └── block-stream@0.0.8
│ ├── text-table@0.2.0
│ ├── uid-number@0.0.6
│ ├── umask@1.1.0
│ ├─┬ unique-filename@1.1.0
│ │ └── unique-slug@2.0.0
│ ├── unpipe@1.0.0
│ ├─┬ validate-npm-package-license@3.0.1
│ │ ├─┬ spdx-correct@1.0.2
│ │ │ └── spdx-license-ids@1.2.0
│ │ └─┬ spdx-expression-parse@1.0.2
│ │   ├── spdx-exceptions@1.0.4
│ │   └── spdx-license-ids@1.2.0
│ ├─┬ validate-npm-package-name@2.2.2
│ │ └── builtins@0.0.7
│ ├─┬ which@1.2.4
│ │ ├─┬ is-absolute@0.1.7
│ │ │ └── is-relative@0.1.3
│ │ └── isexe@1.1.1
│ ├── wrappy@1.0.1
│ └── write-file-atomic@1.1.4
├─┬ request@2.69.0
│ ├── aws-sign2@0.6.0
│ ├─┬ aws4@1.2.1
│ │ └── lru-cache@2.7.3
│ ├─┬ bl@1.0.2
│ │ └─┬ readable-stream@2.0.5
│ │   ├── core-util-is@1.0.2
│ │   ├── inherits@2.0.1
│ │   ├── isarray@0.0.1
│ │   ├── process-nextick-args@1.0.6
│ │   ├── string_decoder@0.10.31
│ │   └── util-deprecate@1.0.2
│ ├── caseless@0.11.0
│ ├─┬ combined-stream@1.0.5
│ │ └── delayed-stream@1.0.0
│ ├── extend@3.0.0
│ ├── forever-agent@0.6.1
│ ├─┬ form-data@1.0.0-rc3
│ │ └── async@1.5.2
│ ├─┬ har-validator@2.0.6
│ │ ├─┬ chalk@1.1.1
│ │ │ ├── ansi-styles@2.1.0
│ │ │ ├── escape-string-regexp@1.0.4
│ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ └── ansi-regex@2.0.0
│ │ │ ├─┬ strip-ansi@3.0.0
│ │ │ │ └── ansi-regex@2.0.0
│ │ │ └── supports-color@2.0.0
│ │ ├─┬ commander@2.9.0
│ │ │ └── graceful-readlink@1.0.1
│ │ ├─┬ is-my-json-valid@2.12.4
│ │ │ ├── generate-function@2.0.0
│ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ └── is-property@1.0.2
│ │ │ ├── jsonpointer@2.0.0
│ │ │ └── xtend@4.0.1
│ │ └─┬ pinkie-promise@2.0.0
│ │   └── pinkie@2.0.4
│ ├─┬ hawk@3.1.3
│ │ ├── boom@2.10.1
│ │ ├── cryptiles@2.0.5
│ │ ├── hoek@2.16.3
│ │ └── sntp@1.0.9
│ ├─┬ http-signature@1.1.1
│ │ ├── assert-plus@0.2.0
│ │ ├─┬ jsprim@1.2.2
│ │ │ ├── extsprintf@1.0.2
│ │ │ ├── json-schema@0.2.2
│ │ │ └── verror@1.3.6
│ │ └─┬ sshpk@1.7.3
│ │   ├── asn1@0.2.3
│ │   ├── dashdash@1.12.2
│ │   ├── ecc-jsbn@0.1.1
│ │   ├── jodid25519@1.0.2
│ │   ├── jsbn@0.1.0
│ │   └── tweetnacl@0.13.3
│ ├── is-typedarray@1.0.0
│ ├── isstream@0.1.2
│ ├── json-stringify-safe@5.0.1
│ ├─┬ mime-types@2.1.9
│ │ └── mime-db@1.21.0
│ ├── node-uuid@1.4.7
│ ├── oauth-sign@0.8.1
│ ├── qs@6.0.2
│ ├── stringstream@0.0.5
│ ├── tough-cookie@2.2.1
│ └── tunnel-agent@0.4.2
└── semver@5.1.0

```

stderr
```
npm ERR! extraneous: lodash._baseuniq@3.0.3 /home/pnorman/osm/kosmtik-3/node_modules/npm/node_modules/lodash._baseuniq
npm ERR! extraneous: lodash._bindcallback@3.0.1 /home/pnorman/osm/kosmtik-3/node_modules/npm/node_modules/lodash._bindcallback
npm ERR! extraneous: lodash.restparam@3.6.1 /home/pnorman/osm/kosmtik-3/node_modules/npm/node_modules/lodash.restparam
npm ERR! not ok code 0
```

```
$ node --version
v0.10.25
```

fwiw, it *was* working, then in the middle of zooming in, it stopped.

**Comment by yohanboniface** [comment]
can you try `npm install mapnik@3.4.7`?

**Comment by pnorman** [comment]
Seems to work now

**Comment by yohanboniface** [comment]
with this specific version or without any change?

**Comment by pnorman** [comment]
with `git clean -xfd && npm install mapnik@3.4.7 && npm install`

**Comment by yohanboniface** [comment]
OK, so I need to investigate the problem with newer Mapnik version.

@springmeyer any clue from the top of your head given the stacktrace on https://github.com/kosmtik/kosmtik/issues/107#issue-132348514 ?

**Comment by nebulon42** [comment]
I didn't notice any problems with latest master and `mapnik@3.4.16`. I have node v4.3.0 though.

**Comment by springmeyer** [comment]
Sorry about this breakage hitting in a patch release. That is my fault - I should have bumped at least the minor of node-mapnik, but this slipped by me. More details (and the recommended workaround) at https://github.com/mapnik/node-mapnik/issues/590.

**Comment by pnorman** [comment]
To follow semver, should a 3.4.17 be released with it reverted and 3.5.0 be released with this change?

**Comment by springmeyer** [comment]
@pnorman v3.4.17 has now been released with a back compatibility fix (https://github.com/mapnik/node-mapnik/blob/master/CHANGELOG.md#3417). Now any invalid indexes will be skipped rather than erroring out. This effectively makes using the new index format opt-in.

**Comment by yohanboniface** [comment]
Cool, thanks Dane, I'll bump explicitly the patch version then :)
