### ISSUE TITLE
Error: No value provided for variable {id}

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#124]
Turning on xray gave me

```

/home/pnorman/osm/kosmtik-3/src/back/Utils.js:23
                throw new Error('No value provided for variable ' + str);
                      ^
Error: No value provided for variable {id}
    at /home/pnorman/osm/kosmtik-3/src/back/Utils.js:23:23
    at String.replace (native)
    at Object.module.exports.template (/home/pnorman/osm/kosmtik-3/src/back/Utils.js:20:20)
    at /home/pnorman/osm/kosmtik-3/src/back/XRayTile.js:37:33
    at Array.reduce (native)
    at XRayTile.styleMap (/home/pnorman/osm/kosmtik-3/src/back/XRayTile.js:34:36)
    at XRayTile.render (/home/pnorman/osm/kosmtik-3/src/back/XRayTile.js:16:25)
    at /home/pnorman/osm/kosmtik-3/src/back/ProjectServer.js:139:19
    at /home/pnorman/osm/kosmtik-3/src/back/VectorBasedTile.js:24:64
```

This is Kosmtik serving a .tm2 project.yml file which specifies ``source: "tmsource:///home/pnorman/osm/osm-clear/osm-clear.tm2source"``

**Comment by pnorman** [comment]
I had a typo on my YAML, using "Layer" instead of "layers" in the .tm2 project.yml

**Comment by nebulon42** [comment]
So I guess that fixed it?! Closing.

**Comment by yohanboniface** [comment]
I think I've kept this issue open as reminder to catch such error and provide a more friendly user message.

**Comment by nebulon42** [comment]
Ok.
