### ISSUE TITLE
cannot accept empty buffer as protobuf

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#126]
When turning on x-ray

```
cannot accept empty buffer as protobuf
Trace
    at ProjectServer.raise (/home/pnorman/osm/kosmtik-3/src/back/ProjectServer.js:239:13)
    at /home/pnorman/osm/kosmtik-3/src/back/ProjectServer.js:137:34
    at /home/pnorman/osm/kosmtik-3/src/back/VectorBasedTile.js:22:28
Unable to parse vector tile data for uri http://192.168.1.1:6789/osm-clear.tm2source/tile/7/24/43.pbf
```

There are tiles with no objects expected in them

**Comment by yohanboniface** [comment]
I think it's same issue than #125, i.e. V2 tiles not valid by spec.
I'm closing here to follow up there.

**Comment by pnorman** [comment]
#125 is fixed but this still happens - can you reopen?

**Comment by pnorman** [comment]
Current traceback is

```
cannot accept empty buffer as protobuf
Trace
    at ProjectServer.raise (/home/pnorman/osm/kosmtik-3/src/back/ProjectServer.js:239:13)
    at /home/pnorman/osm/kosmtik-3/src/back/ProjectServer.js:73:34
    at /home/pnorman/osm/kosmtik-3/src/back/VectorBasedTile.js:78:18
    at /home/pnorman/osm/kosmtik-3/src/back/VectorBasedTile.js:37:28
```

**Comment by rory** [comment]
I am also getting this problem with Kosmtik. My server is sending zero-bytes for a certain (empty) vector tile. Other software that uses vectortiles (e.g. tessera) can work with this.
