### ISSUE TITLE
Overwriting source in vector tile using style doesn't work

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#127]
With

project.yml
```yml
source: "tmsource:///path/to/osm-clear.tm2source"
```
localconfig.json
```json
[
  {
    "where":"source",
    "then":"tmsource:///home/pnorman/osm/osm-clear/osm-clear.tm2source"
  }
]
```

`node index.js serve --host 192.168.1.1 ~/osm/osm-clear/osm-clear.tm2/project.yml` gets the error

```
[Local Config] Patched config from /home/pnorman/osm/osm-clear/osm-clear.tm2/localconfig.json
[datasource loader] Loading source from /path/to/osm-clear.tm2source

fs.js:684
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/path'
    at Object.fs.lstatSync (fs.js:684:18)
    at Object.realpathSync (fs.js:1270:21)
    at new Project (/home/pnorman/osm/kosmtik-3/src/back/Project.js:12:59)
    at DataSourceLoader.loadLocalSource (/home/pnorman/osm/kosmtik-3/src/plugins/datasource-loader/index.js:50:19)
    at DataSourceLoader.patchMML (/home/pnorman/osm/kosmtik-3/src/plugins/datasource-loader/index.js:34:48)
    at null.<anonymous> (/home/pnorman/osm/kosmtik-3/src/back/StateBase.js:35:74)
    at done (/home/pnorman/osm/kosmtik-3/src/plugins/local-config/index.js:14:23)
    at /home/pnorman/osm/kosmtik-3/src/plugins/local-config/index.js:52:13
    at /home/pnorman/osm/kosmtik-3/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
    at fs.js:268:14
```

**Comment by yohanboniface** [comment]
Humm, yeah, I think at MML patching time, the source is already in extended format.
I'll have a look.
