### ISSUE TITLE
Error: No value provided for variable {host}

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#130]
```
[datasource loader] Loading source from /home/pnorman/osm/osm-clear/osm-clear.tm2source

/home/pnorman/osm/kosmtik-3/src/back/Utils.js:23
                throw new Error('No value provided for variable ' + str);
                      ^
Error: No value provided for variable {host}
    at /home/pnorman/osm/kosmtik-3/src/back/Utils.js:23:23
    at String.replace (native)
    at Object.module.exports.template (/home/pnorman/osm/kosmtik-3/src/back/Utils.js:20:20)
    at DataSourceLoader.attachSourceUrl (/home/pnorman/osm/kosmtik-3/src/plugins/datasource-loader/index.js:62:24)
    at DataSourceLoader.loadLocalSource (/home/pnorman/osm/kosmtik-3/src/plugins/datasource-loader/index.js:51:10)
    at DataSourceLoader.patchMML (/home/pnorman/osm/kosmtik-3/src/plugins/datasource-loader/index.js:34:48)
    at null.<anonymous> (/home/pnorman/osm/kosmtik-3/src/back/StateBase.js:35:74)
    at done (/home/pnorman/osm/kosmtik-3/src/plugins/local-config/index.js:14:23)
    at LocalConfig.patchMML (/home/pnorman/osm/kosmtik-3/src/plugins/local-config/index.js:31:16)
    at null.<anonymous> (/home/pnorman/osm/kosmtik-3/src/back/StateBase.js:35:74)
```

I can use the style with `node index.js serve  project.yml`

**Comment by yohanboniface** [comment]
May be fixed by https://github.com/kosmtik/kosmtik/commit/dcd58cf2a8c30e037b8bacce907b9a08fd87426d

Can you have a try?

**Comment by pnorman** [comment]
:
