### ISSUE TITLE
Requesting out of range tiles crashes Kosmtik

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#164]
Requesting http://192.168.1.1:6789/osm-clear.tm2source/tile/4/16/16.pbf gave me the error

```
/home/pnorman/osm/kosmtik-3/src/back/Tile.js:40
    var surface = new mapnik.VectorTile(this.z, this.x, this.y);
                  ^
TypeError: required parameter x is out of range of possible values based on z value
    at Tile.renderToVector (/home/pnorman/osm/kosmtik-3/src/back/Tile.js:40:19)
    at /home/pnorman/osm/kosmtik-3/src/back/ProjectServer.js:118:21
    at /home/pnorman/osm/kosmtik-3/node_modules/generic-pool/lib/generic-pool.js:347:9
    at loaded (/home/pnorman/osm/kosmtik-3/src/back/MapPool.js:28:28)
```

**Comment by yohanboniface** [comment]
Should we wrap?

**Comment by pnorman** [comment]
We should return an error, probably HTTP 400.
