### ISSUE TITLE
str.replace error

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#17]
```
[httpserver] /mq-carto-style.tm2/reload/ 200

/home/pnorman/kosmtik/src/back/Utils.js:20
        return str.replace(/\{ *([\w_]+) *\}/g, function (str, key) {
                   ^
TypeError: Cannot call method 'replace' of undefined
    at Object.module.exports.template (/home/pnorman/kosmtik/src/back/Utils.js:20:20)
    at VectorBasedTile._render (/home/pnorman/kosmtik/src/back/VectorBasedTile.js:35:24)
    at VectorBasedTile.render (/home/pnorman/kosmtik/src/back/VectorBasedTile.js:44:10)
    at /home/pnorman/kosmtik/src/back/ProjectServer.js:55:21
    at /home/pnorman/kosmtik/node_modules/generic-pool/lib/generic-pool.js:281:11
    at loaded (/home/pnorman/kosmtik/src/back/MapPool.js:28:28)
```

Occurred when saving a file from my editor.

**Comment by yohanboniface** [comment]
Do you have encountered this bug again, @pnorman?

**Comment by pnorman** [comment]
I'm hitting this again
