### ISSUE TITLE
Requires a new version of Mapnik

### ISSUE THREAD

**Issue by Juko** [kosmtik/kosmtik#182]
Hey, after I `npm install`, everything builds correctly, but upon trying to run `index.js` I get this error. 

```
$ ./index.js
module.js:568
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/Users/juko/Documents/mapping/kosmtik/node_modules/mapnik/lib/binding/node-v48-darwin-x64/mapnik.node, 1): Library not loaded: /usr/local/lib/libmapnik.dylib
  Referenced from: /Users/juko/Documents/mapping/kosmtik/node_modules/mapnik/lib/binding/node-v48-darwin-x64/mapnik.node
  Reason: Incompatible library version: mapnik.node requires version 3.0.11 or later, but libmapnik.dylib provides version 3.0.9
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/juko/Documents/mapping/kosmtik/node_modules/mapnik/lib/mapnik.js:31:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

I believe I have the latest version of mapnik, and I've tried removing the node_modules folder and npm install again. My npm list is below

```
$ npm list
kosmtik@0.0.13 /Users/juko/Documents/mapping/kosmtik
├── abbrev@1.0.9
├── aproba@1.0.4
├── asap@2.0.5
├─┬ carto@0.16.3
│ ├── chroma-js@1.1.1
│ ├── husl@6.0.1
│ ├── lodash@4.16.4
│ ├── mapnik-reference@8.5.5
│ └─┬ yargs@4.8.1
│   ├─┬ cliui@3.2.0
│   │ ├─┬ strip-ansi@3.0.1
│   │ │ └── ansi-regex@2.0.0
│   │ └── wrap-ansi@2.0.0
│   ├── decamelize@1.2.0
│   ├── get-caller-file@1.0.2
│   ├── lodash.assign@4.2.0
│   ├─┬ os-locale@1.4.0
│   │ └─┬ lcid@1.0.0
│   │   └── invert-kv@1.0.0
│   ├─┬ read-pkg-up@1.0.1
│   │ ├─┬ find-up@1.1.2
│   │ │ └── path-exists@2.1.0
│   │ └─┬ read-pkg@1.1.0
│   │   ├─┬ load-json-file@1.1.0
│   │   │ ├── graceful-fs@4.1.9
│   │   │ ├─┬ parse-json@2.2.0
│   │   │ │ └─┬ error-ex@1.3.0
rayish@0.2.1
│   │   │ ├── pify@2.3.0
│   │   │ └─┬ strip-bom@2.0.0
│   │   │   └── is-utf8@0.2.1
│   │   ├─┬ normalize-package-data@2.3.5
│   │   │ ├── hosted-git-info@2.1.5
│   │   │ ├─┬ is-builtin-module@1.0.0
│   │   │ │ └── builtin-modules@1.1.1
│   │   │ └─┬ validate-npm-package-license@3.0.1
│   │   │   ├─┬ spdx-correct@1.0.2
│   │   │   │ └── spdx-license-ids@1.2.2
│   │   │   └── spdx-expression-parse@1.0.4
│   │   └── path-type@1.1.0
│   ├── require-directory@2.1.1
│   ├── require-main-filename@1.0.1
│   ├── set-blocking@2.0.0
│   ├─┬ string-width@1.0.2
│   │ ├─┬ code-point-at@1.0.1
│   │ │ └── number-is-nan@1.0.1
│   │ └── is-fullwidth-code-point@1.0.0
│   ├── which-module@1.0.0
│   ├── window-size@0.2.0
│   ├── y18n@3.2.1
│   └─┬ yargs-parser@2.4.1
│     └── camelcase@3.0.0
├─┬ config-chain@1.1.11
│ └── proto-list@1.2.4
├── fstream@1.0.10
├─┬ fstream-npm@1.2.0
│ └─┬ fstream-ignore@1.0.5
│   └─┬ minimatch@3.0.3
│     └─┬ brace-expansion@1.1.6
│       ├── balanced-match@0.4.2
│       └── concat-map@0.0.1
├── generic-pool@2.4.3
├─┬ glob@7.1.0
│ ├── fs.realpath@1.0.0
│ ├─┬ minimatch@3.0.3
│ │ └─┬ brace-expansion@1.1.6
│ │   ├── balanced-match@0.4.2
│ │   └── concat-map@0.0.1
│ └── path-is-absolute@1.0.1
├── graceful-fs@4.1.9
├── has-unicode@2.0.1
├── inherits@2.0.3
├─┬ js-yaml@3.6.1
│ ├─┬ argparse@1.0.9
│ │ └── sprintf-js@1.0.3
│ └── esprima@2.7.3
├── json-localizer@0.0.3
├── leaflet@1.0.1
├── leaflet-formbuilder@0.2.3
├── leaflet-hash@0.2.1
├── lockfile@1.0.2
├── lodash.clonedeep@4.5.0
├── lodash.union@4.6.0
├── lodash.uniq@4.5.0
├── lodash.without@4.4.0
├─┬ mapnik@3.5.13
│ ├── mapnik-vector-tile@1.2.0
│ ├── nan@2.2.1
│ └── protozero@1.3.0
├─┬ minimatch@3.0.3
│ └─┬ brace-expansion@1.1.6
│   ├── balanced-match@0.4.2
│   └── concat-map@0.0.1
├─┬ mocha@2.5.3
│ ├── commander@2.3.0
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── diff@1.4.0
│ ├── escape-string-regexp@1.0.2
│ ├─┬ glob@3.2.11
│ │ ├── inherits@2.0.3
│ │ └─┬ minimatch@0.3.0
│ │   ├── lru-cache@2.7.3
│ │   └── sigmund@1.0.1
│ ├── growl@1.9.2
│ ├─┬ jade@0.26.3
│ │ ├── commander@0.6.1
│ │ └── mkdirp@0.3.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── supports-color@1.2.0
│ └── to-iso-string@0.0.2
├─┬ node-gyp@3.4.0
│ ├─┬ minimatch@3.0.3
│ │ └─┬ brace-expansion@1.1.6
│ │   ├── balanced-match@0.4.2
│ │   └── concat-map@0.0.1
│ ├─┬ npmlog@3.1.2
│ │ ├─┬ are-we-there-yet@1.1.2
│ │ │ └── delegates@1.0.0
│ │ ├── console-control-strings@1.1.0
│ │ ├─┬ gauge@2.6.0
│ │ │ ├── has-color@0.1.7
│ │ │ ├── object-assign@4.1.0
│ │ │ ├── signal-exit@3.0.0
│ │ │ ├─┬ string-width@1.0.2
│ │ │ │ ├─┬ code-point-at@1.0.0
│ │ │ │ │ └── number-is-nan@1.0.0
│ │ │ │ └─┬ is-fullwidth-code-point@1.0.0
│ │ │ │   └── number-is-nan@1.0.0
│ │ │ └── wide-align@1.1.0
│ │ └── set-blocking@2.0.0
│ └─┬ path-array@1.0.1
│   └─┬ array-index@1.0.0
│     ├─┬ debug@2.2.0
│     │ └── ms@0.7.1
│     └─┬ es6-symbol@3.1.0
│       ├── d@0.1.1
│       └─┬ es5-ext@0.10.12
│         └── es6-iterator@2.0.0
├─┬ node-pre-gyp@0.6.31
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ nopt@3.0.6
│ │ └── abbrev@1.0.9
│ ├─┬ npmlog@4.0.0
│ │ ├─┬ are-we-there-yet@1.1.2
│ │ │ └── delegates@1.0.0
│ │ ├── console-control-strings@1.1.0
│ │ ├─┬ gauge@2.6.0
│ │ │ ├── aproba@1.0.4
│ │ │ ├── has-color@0.1.7
│ │ │ ├── has-unicode@2.0.1
│ │ │ ├── object-assign@4.1.0
│ │ │ ├── signal-exit@3.0.1
│ │ │ ├─┬ string-width@1.0.2
│ │ │ │ ├─┬ code-point-at@1.0.1
│ │ │ │ │ └── number-is-nan@1.0.1
│ │ │ │ └── is-fullwidth-code-point@1.0.0
│ │ │ ├─┬ strip-ansi@3.0.1
│ │ │ │ └── ansi-regex@2.0.0
│ │ │ └── wide-align@1.1.0
│ │ └── set-blocking@2.0.0
│ ├─┬ rc@1.1.6
│ │ ├── deep-extend@0.4.1
│ │ ├── ini@1.3.4
│ │ ├── minimist@1.2.0
│ │ └── strip-json-comments@1.0.4
│ ├─┬ request@2.76.0
│ │ ├── aws-sign2@0.6.0
│ │ ├── aws4@1.5.0
│ │ ├── caseless@0.11.0
│ │ ├─┬ combined-stream@1.0.5
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.0
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@2.1.1
│ │ │ └── asynckit@0.4.0
│ │ ├─┬ har-validator@2.0.6
│ │ │ ├─┬ chalk@1.1.3
│ │ │ │ ├── ansi-styles@2.2.1
│ │ │ │ ├── escape-string-regexp@1.0.5
│ │ │ │ ├── has-ansi@2.0.0
│ │ │ │ └── supports-color@2.0.0
│ │ │ ├─┬ commander@2.9.0
│ │ │ │ └── graceful-readlink@1.0.1
│ │ │ ├─┬ is-my-json-valid@2.15.0
│ │ │ │ ├── generate-function@2.0.0
│ │ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ │ └── is-property@1.0.2
│ │ │ │ ├── jsonpointer@4.0.0
│ │ │ │ └── xtend@4.0.1
│ │ │ └─┬ pinkie-promise@2.0.1
│ │ │   └── pinkie@2.0.4
│ │ ├─┬ hawk@3.1.3
│ │ │ ├── boom@2.10.1
│ │ │ ├── cryptiles@2.0.5
│ │ │ ├── hoek@2.16.3
│ │ │ └── sntp@1.0.9
│ │ ├─┬ http-signature@1.1.1
│ │ │ ├── assert-plus@0.2.0
│ │ │ ├─┬ jsprim@1.3.1
│ │ │ │ ├── extsprintf@1.0.2
│ │ │ │ ├── json-schema@0.2.3
│ │ │ │ └── verror@1.3.6
│ │ │ └─┬ sshpk@1.10.1
│ │ │   ├── asn1@0.2.3
│ │ │   ├── assert-plus@1.0.0
│ │ │   ├── bcrypt-pbkdf@1.0.0
│ │ │   ├─┬ dashdash@1.14.0
│ │ │   │ └── assert-plus@1.0.0
│ │ │   ├── ecc-jsbn@0.1.1
│ │ │   ├─┬ getpass@0.1.6
│ │ │   │ └── assert-plus@1.0.0
│ │ │   ├── jodid25519@1.0.2
│ │ │   ├── jsbn@0.1.0
│ │ │   └── tweetnacl@0.14.3
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.1.12
│ │ │ └── mime-db@1.24.0
│ │ ├── node-uuid@1.4.7
│ │ ├── oauth-sign@0.8.2
│ │ ├── qs@6.3.0
│ │ ├── stringstream@0.0.5
│ │ ├─┬ tough-cookie@2.3.2
│ │ │ └── punycode@1.4.1
│ │ └── tunnel-agent@0.4.3
│ ├─┬ rimraf@2.5.4
│ │ └─┬ glob@7.1.1
│ │   ├── fs.realpath@1.0.0
│ │   ├── inflight@1.0.6
│ │   ├─┬ minimatch@3.0.3
│ │   │ └─┬ brace-expansion@1.1.6
│ │   │   ├── balanced-match@0.4.2
│ │   │   └── concat-map@0.0.1
│ │   ├── once@1.4.0
│ │   └── path-is-absolute@1.0.1
│ ├── semver@5.3.0
│ ├─┬ tar@2.2.1
│ │ ├── block-stream@0.0.9
│ │ ├─┬ fstream@1.0.10
│ │ │ └── graceful-fs@4.1.9
│ │ └── inherits@2.0.3
│ └─┬ tar-pack@3.3.0
│   ├─┬ debug@2.2.0
│   │ └── ms@0.7.1
│   ├── fstream-ignore@1.0.5
│   ├─┬ once@1.3.3
│   │ └── wrappy@1.0.2
│   ├─┬ readable-stream@2.1.5
│   │ ├── buffer-shims@1.0.0
│   │ ├── core-util-is@1.0.2
│   │ ├── isarray@1.0.0
│   │ ├── process-nextick-args@1.0.7
│   │ ├── string_decoder@0.10.31
│   │ └── util-deprecate@1.0.2
│   └── uid-number@0.0.6
├─┬ nomnom@1.8.1
│ ├─┬ chalk@0.4.0
│ │ ├── ansi-styles@1.0.0
│ │ ├── has-color@0.1.7
│ │ └── strip-ansi@0.1.1
│ └── underscore@1.6.0
├─┬ npm@3.10.9
│ ├── ansi-regex@2.0.0
│ ├── ansicolors@0.3.2
│ ├── ansistyles@0.1.3
│ ├── archy@1.0.0
│ ├── chownr@1.0.1
│ ├── cmd-shim@2.0.2
│ ├─┬ columnify@1.5.4
│ │ └─┬ wcwidth@1.0.0
│ │   └─┬ defaults@1.0.3
│ │     └── clone@1.0.2
│ ├── debuglog@1.0.1
│ ├── dezalgo@1.0.3
│ ├── editor@1.0.0
│ ├── fs-vacuum@1.2.9
│ ├── fs-write-stream-atomic@1.0.8
│ ├── hosted-git-info@2.1.5
│ ├── iferr@0.1.5
│ ├── imurmurhash@0.1.4
│ ├── inflight@1.0.5
│ ├── ini@1.3.4
│ ├─┬ init-package-json@1.9.4
│ │ ├─┬ glob@6.0.4
│ │ │ ├─┬ minimatch@3.0.3
│ │ │ │ └─┬ brace-expansion@1.1.6
│ │ │ │   ├── balanced-match@0.4.2
│ │ │ │   └── concat-map@0.0.1
│ │ │ └── path-is-absolute@1.0.0
│ │ └── promzard@0.3.0
│ ├── lodash._baseindexof@3.1.0
│ ├─┬ lodash._baseuniq@4.6.0
│ │ ├── lodash._createset@4.0.3
│ │ └── lodash._root@3.0.1
│ ├── lodash._bindcallback@3.0.1
│ ├── lodash._cacheindexof@3.0.2
│ ├── lodash._createcache@3.1.2
│ ├── lodash._getnative@3.9.1
│ ├── lodash.restparam@3.6.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── nopt@3.0.6
│ ├── normalize-git-url@3.0.2
│ ├─┬ normalize-package-data@2.3.5
│ │ └─┬ is-builtin-module@1.0.0
│ │   └── builtin-modules@1.1.1
│ ├── npm-cache-filename@1.0.2
│ ├── npm-install-checks@3.0.0
│ ├─┬ osenv@0.1.3
│ │ ├── os-homedir@1.0.1
│ │ └── os-tmpdir@1.0.1
│ ├─┬ read@1.0.7
│ │ └── mute-stream@0.0.5
│ ├── read-cmd-shim@1.0.1
│ ├─┬ read-installed@4.0.3
│ │ └── util-extend@1.0.3
│ ├─┬ read-package-json@2.0.4
│ │ ├─┬ glob@6.0.4
│ │ │ └── path-is-absolute@1.0.0
│ │ └─┬ json-parse-helpfulerror@1.0.3
│ │   └── jju@1.3.0
│ ├── readdir-scoped-modules@1.0.2
│ ├── realize-package-specifier@3.0.3
│ ├─┬ request@2.75.0
│ │ ├── aws-sign2@0.6.0
│ │ ├── aws4@1.4.1
│ │ ├─┬ bl@1.1.2
│ │ │ └─┬ readable-stream@2.0.6
│ │ │   ├── core-util-is@1.0.2
│ │ │   ├── isarray@1.0.0
│ │ │   ├── process-nextick-args@1.0.7
│ │ │   ├── string_decoder@0.10.31
│ │ │   └── util-deprecate@1.0.2
│ │ ├── caseless@0.11.0
│ │ ├─┬ combined-stream@1.0.5
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.0
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@2.0.0
│ │ │ └── asynckit@0.4.0
│ │ ├─┬ har-validator@2.0.6
│ │ │ ├─┬ chalk@1.1.3
│ │ │ │ ├── ansi-styles@2.2.1
│ │ │ │ ├── escape-string-regexp@1.0.5
│ │ │ │ ├── has-ansi@2.0.0
│ │ │ │ └── supports-color@2.0.0
│ │ │ ├─┬ commander@2.9.0
│ │ │ │ └── graceful-readlink@1.0.1
│ │ │ ├─┬ is-my-json-valid@2.15.0
│ │ │ │ ├── generate-function@2.0.0
│ │ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ │ └── is-property@1.0.2
│ │ │ │ ├── jsonpointer@4.0.0
│ │ │ │ └── xtend@4.0.1
│ │ │ └─┬ pinkie-promise@2.0.1
│ │ │   └── pinkie@2.0.4
│ │ ├─┬ hawk@3.1.3
│ │ │ ├── boom@2.10.1
│ │ │ ├── cryptiles@2.0.5
│ │ │ ├── hoek@2.16.3
│ │ │ └── sntp@1.0.9
│ │ ├─┬ http-signature@1.1.1
│ │ │ ├── assert-plus@0.2.0
│ │ │ ├─┬ jsprim@1.3.1
│ │ │ │ ├── extsprintf@1.0.2
│ │ │ │ ├── json-schema@0.2.3
│ │ │ │ └── verror@1.3.6
│ │ │ └─┬ sshpk@1.10.1
│ │ │   ├── asn1@0.2.3
│ │ │   ├── assert-plus@1.0.0
│ │ │   ├── bcrypt-pbkdf@1.0.0
│ │ │   ├── dashdash@1.14.0
│ │ │   ├── ecc-jsbn@0.1.1
│ │ │   ├── getpass@0.1.6
│ │ │   ├── jodid25519@1.0.2
│ │ │   ├── jsbn@0.1.0
│ │ │   └── tweetnacl@0.14.3
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.1.12
│ │ │ └── mime-db@1.24.0
│ │ ├── node-uuid@1.4.7
│ │ ├── oauth-sign@0.8.2
│ │ ├── qs@6.2.1
│ │ ├── stringstream@0.0.5
│ │ ├── tough-cookie@2.3.1
│ │ └── tunnel-agent@0.4.3
│ ├── semver@5.3.0
│ ├── sha@2.0.1
│ ├── slide@1.1.6
│ ├── strip-ansi@3.0.1
│ ├─┬ tar@2.2.1
│ │ └── block-stream@0.0.8
│ ├── text-table@0.2.0
│ ├── uid-number@0.0.6
│ ├── umask@1.1.0
│ ├─┬ unique-filename@1.1.0
│ │ └── unique-slug@2.0.0
│ ├── unpipe@1.0.0
│ ├─┬ validate-npm-package-license@3.0.1
│ │ ├─┬ spdx-correct@1.0.2
│ │ │ └── spdx-license-ids@1.2.0
│ │ └─┬ spdx-expression-parse@1.0.2
│ │   ├── spdx-exceptions@1.0.4
│ │   └── spdx-license-ids@1.2.0
│ └─┬ validate-npm-package-name@2.2.2
│   └── builtins@0.0.7
├── npm-package-arg@4.2.0
├─┬ npm-registry-client@7.2.1
│ ├─┬ concat-stream@1.5.2
│ │ ├─┬ readable-stream@2.0.6
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── isarray@1.0.0
│ │ │ ├── process-nextick-args@1.0.7
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ └── typedarray@0.0.6
│ ├─┬ npmlog@3.1.2
│ │ ├─┬ are-we-there-yet@1.1.2
│ │ │ └── delegates@1.0.0
│ │ ├── console-control-strings@1.1.0
│ │ ├─┬ gauge@2.6.0
│ │ │ ├── has-color@0.1.7
│ │ │ ├── object-assign@4.1.0
│ │ │ ├── signal-exit@3.0.0
│ │ │ ├─┬ string-width@1.0.2
│ │ │ │ ├─┬ code-point-at@1.0.0
│ │ │ │ │ └── number-is-nan@1.0.0
│ │ │ │ └─┬ is-fullwidth-code-point@1.0.0
│ │ │ │   └── number-is-nan@1.0.0
│ │ │ └── wide-align@1.1.0
│ │ └── set-blocking@2.0.0
│ └── retry@0.10.0
├── npm-user-validate@0.1.5
├─┬ npmlog@4.0.0
│ ├─┬ are-we-there-yet@1.1.2
│ │ └── delegates@1.0.0
│ ├── console-control-strings@1.1.0
│ ├─┬ gauge@2.6.0
│ │ ├── has-color@0.1.7
│ │ ├── object-assign@4.1.0
│ │ ├── signal-exit@3.0.0
│ │ ├─┬ string-width@1.0.2
│ │ │ ├─┬ code-point-at@1.0.0
│ │ │ │ └── number-is-nan@1.0.0
│ │ │ └─┬ is-fullwidth-code-point@1.0.0
│ │ │   └── number-is-nan@1.0.0
│ │ └── wide-align@1.1.0
│ └── set-blocking@2.0.0
├── once@1.4.0
├── opener@1.4.2
├── path-is-inside@1.0.2
├── read-package-tree@5.1.5
├─┬ readable-stream@2.1.5
│ ├── buffer-shims@1.0.0
│ ├── core-util-is@1.0.2
│ ├── isarray@1.0.0
│ ├── process-nextick-args@1.0.7
│ ├── string_decoder@0.10.31
│ └── util-deprecate@1.0.2
├─┬ request@2.76.0
│ ├── aws-sign2@0.6.0
│ ├── aws4@1.5.0
│ ├── caseless@0.11.0
│ ├─┬ combined-stream@1.0.5
│ │ └── delayed-stream@1.0.0
│ ├── extend@3.0.0
│ ├── forever-agent@0.6.1
│ ├─┬ form-data@2.1.1
│ │ └── asynckit@0.4.0
│ ├─┬ har-validator@2.0.6
│ │ ├─┬ chalk@1.1.3
│ │ │ ├── ansi-styles@2.2.1
│ │ │ ├── escape-string-regexp@1.0.5
│ │ │ ├── has-ansi@2.0.0
│ │ │ └── supports-color@2.0.0
│ │ ├─┬ commander@2.9.0
│ │ │ └── graceful-readlink@1.0.1
│ │ ├─┬ is-my-json-valid@2.15.0
│ │ │ ├── generate-function@2.0.0
│ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ └── is-property@1.0.2
│ │ │ ├── jsonpointer@4.0.0
│ │ │ └── xtend@4.0.1
│ │ └─┬ pinkie-promise@2.0.1
│ │   └── pinkie@2.0.4
│ ├─┬ hawk@3.1.3
│ │ ├── boom@2.10.1
│ │ ├── cryptiles@2.0.5
│ │ ├── hoek@2.16.3
│ │ └── sntp@1.0.9
│ ├─┬ http-signature@1.1.1
│ │ ├── assert-plus@0.2.0
│ │ ├─┬ jsprim@1.3.1
│ │ │ ├── extsprintf@1.0.2
│ │ │ ├── json-schema@0.2.3
│ │ │ └── verror@1.3.6
│ │ └─┬ sshpk@1.10.1
│ │   ├── asn1@0.2.3
│ │   ├── assert-plus@1.0.0
│ │   ├── bcrypt-pbkdf@1.0.0
│ │   ├─┬ dashdash@1.14.0
│ │   │ └── assert-plus@1.0.0
│ │   ├── ecc-jsbn@0.1.1
│ │   ├─┬ getpass@0.1.6
│ │   │ └── assert-plus@1.0.0
│ │   ├── jodid25519@1.0.2
│ │   ├── jsbn@0.1.0
│ │   └── tweetnacl@0.14.3
│ ├── is-typedarray@1.0.0
│ ├── isstream@0.1.2
│ ├── json-stringify-safe@5.0.1
│ ├─┬ mime-types@2.1.12
│ │ └── mime-db@1.24.0
│ ├── node-uuid@1.4.7
│ ├── oauth-sign@0.8.2
│ ├── qs@6.3.0
│ ├── stringstream@0.0.5
│ ├─┬ tough-cookie@2.3.2
│ │ └── punycode@1.4.1
│ └── tunnel-agent@0.4.3
├── retry@0.10.0
├── rimraf@2.5.4
├── semver@5.3.0
├── sorted-object@2.0.1
├─┬ which@1.2.11
│ └── isexe@1.1.2
├── wrappy@1.0.2
└── write-file-atomic@1.2.0
```

**Comment by nebulon42** [comment]
From different clues I deduced that you are on macOS. There seems to be a problem (version mismatch) with the binary that got downloaded for node-mapnik. I think there is not much we can do about that here. You could either give node-mapnik 3.5.14 a try by issuing `npm install mapnik@3.5.14` or try to downgrade to an earlier node-mapnik version and see if that works. Or open a ticket at https://github.com/mapnik/node-mapnik.

**Comment by Juko** [comment]
Thanks, downloaded 3.5.14 and changed it in the package.json and it worked!
