### ISSUE TITLE
TypeError: vtile.parse is not a function

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#188]
```
/home/pnorman/osm/meddo/node_modules/kosmtik/src/back/XRayTile.js:20
        vtile.parse();
              ^

TypeError: vtile.parse is not a function
    at XRayTile.render (/home/pnorman/osm/meddo/node_modules/kosmtik/src/back/XRayTile.js:20:15)
    at /home/pnorman/osm/meddo/node_modules/kosmtik/src/back/ProjectServer.js:139:19
```

yaml file is a tm2source yaml, and I turned on data inspector

**Comment by pnorman** [comment]
the version from `npm install` didn't work, but going from source did.
