### ISSUE TITLE
Do not throw error when no localconfig option specified and default local config file not found

### ISSUE THREAD

**Issue by nebulon42** [kosmtik/kosmtik#202]
````
[Local Config] Unable to load local config from /path/to/default/localconfig.js
Error: File not found: /path/to/default/localconfig.js
    at Project.LocalConfig.patchMML (kosmtik/src/plugins/local-config/index.js:30:15)
    at Project.<anonymous> (kosmtik/src/back/StateBase.js:35:74)
    at PluginsManager.handleProject (kosmtik/src/back/PluginsManager.js:186:15)
    at Project.<anonymous> (kosmtik/src/back/StateBase.js:35:74)
    at kosmtik/src/back/Project.js:141:19
    at kosmtik/src/back/Utils.js:10:18
    at FSReqWrap.oncomplete (fs.js:123:15)
````

**Comment by tomhughes** [comment]
This is causing two tests to fail in 0.0.14 as released.

**Comment by tomhughes** [comment]
Hmm maybe it's just noise.
