### ISSUE TITLE
issues with OpenStreetMap Carto release v3.0.0 

### ISSUE THREAD

**Issue by mmd-osm** [kosmtik/kosmtik#207]
Recently, project.yaml was renamed to project.mml (https://github.com/gravitystorm/openstreetmap-carto/pull/2473). This change seems to cause some issues with kosmtik:

/usr/local/lib/node_modules/kosmtik/index.js  serve ~/openstreetmap-carto/project.mml

```
[Core] Loading config from /home/mmd/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading plugin from kosmtik-overpass-layer
[Core] Loading project from /home/mmd/openstreetmap-carto/project.mml
undefined:1
scale: 1
^

SyntaxError: Unexpected token s
    at Object.parse (native)
    at Loader.loadFile (/usr/local/lib/node_modules/kosmtik/src/back/loader/MML.js:11:17)
    at BaseLoader.load (/usr/local/lib/node_modules/kosmtik/src/back/loader/Base.js:74:21)
    at Project.load (/usr/local/lib/node_modules/kosmtik/src/back/Project.js:37:23)
```

Adding a symlink ( `ln -s project.mml project.yaml`) and using the very same file with *.yaml* extension fixes the issue.

```
/usr/local/lib/node_modules/kosmtik/index.js  serve ~/openstreetmap-carto/project.yaml
[Core] Loading config from /home/mmd/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading plugin from kosmtik-overpass-layer
[Core] Loading project from /home/mmd/openstreetmap-carto/project.yaml
[Core] PreviewServer started, you can browse http://127.0.0.1:6789
[Local Config] Unable to load local config from /home/mmd/openstreetmap-carto/localconfig.js
[Error: File not found: /home/mmd/openstreetmap-carto/localconfig.js]
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.0.0
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
``` 

![grafik](https://cloud.githubusercontent.com/assets/5842757/21427221/76fa4e00-c853-11e6-8ba1-a43a5f1c2626.png)

Not sure how to proceed here...

**Comment by yohanboniface** [comment]
Which version of Kosmtik are you using?

**Comment by mmd-osm** [comment]
It's the very latest commit in the master branch: 7bcb0b2f61b2c4f171f7328e82ce8326a1313bae

**Comment by mmd-osm** [comment]
Oh, sorry, I though I was using the most recent one, but then used `npm -g install kosmtik` ... bummer. 

Now really trying the latest version look much better:

```
nodejs index.js  serve ~/openstreetmap-carto/project.mml
[Core] Loading config from /home/mmd/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading plugin from kosmtik-overpass-layer
[Core] Loading project from /home/dan/openstreetmap-carto/project.mml
[Core] PreviewServer started, you can browse http://127.0.0.1:6789
[Core] Creating metatiles cache dir tmp/openstreetmap-carto/meta
[Core] Deleting previous metatiles tmp/openstreetmap-carto/meta
[Core] Created vector cache dir tmp/openstreetmap-carto/vector
[Local Config] Unable to load local config from /home/mmd/openstreetmap-carto/localconfig.js
[Error: File not found: /home/mmd/openstreetmap-carto/localconfig.js]
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.0.12
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
```

**Comment by nebulon42** [comment]
@yohanboniface I think we either need to change the readme again or make a new release on npm.

**Comment by nebulon42** [comment]
Closing as new release is triggered.
