### ISSUE TITLE
return process.dlopen(module, path._makeLong(filename))

### ISSUE THREAD

**Issue by abc3660170** [kosmtik/kosmtik#208]
I'm a PC user
C:\Users\Tao\AppData\Roaming\npm\node_modules\kosmtik>node index.js -h
module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\Tao\AppData\Roaming\npm\node_modules\kosmtik\node_modules\mapnik\lib\binding\node-v46-win32-x64\mapnik.node
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Tao\AppData\Roaming\npm\node_modules\kosmtik\node_modules\mapnik\lib\mapnik.js:31:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

**Comment by nebulon42** [comment]
Seems like an issue with node-mapnik. What is your node.js version? You could experiment with some other node-mapnik versions (installable with `npm install mapnik@x.y.z`) and see if that works for you.
