### ISSUE TITLE
Can't install on Ubuntu 16.04.1

### ISSUE THREAD

**Issue by MaelREBOUX** [kosmtik/kosmtik#212]
Hello.

Have hesitate to post here because it is difficult to me to say if I'm really wrong with the way to install.

What is wrong with this above ? I think I have the latest versions of node.js and npm ?

```bash
# apt-get install node.js
# nodejs -v
v4.2.6

# apt-get upgrade npm

# npm install -g n

# npm -g install kosmtik
npm WARN deprecated carto@0.15.3: This module is now under the @mapbox namespace: install @mapbox/carto instead
npm WARN lifecycle mapnik@3.5.14~preinstall: cannot run in wd %s %s (wd=%s) mapnik@3.5.14 npm install node-pre-gyp /usr/local/lib/node_modules/.staging/mapnik-b95e22e5

> mapnik@3.5.14 install /usr/local/lib/node_modules/kosmtik/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.14 and node@7.4.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/osm/.node-gyp/7.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/build'
make: *** No rule to make target '../.node-gyp/7.4.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/kosmtik/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-57-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/kosmtik/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding/node-v51-linux-x64/mapnik.node" "--module_name=mapnik" "--module_path=/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding/node-v51-linux-x64"
gyp ERR! cwd /usr/local/lib/node_modules/kosmtik/node_modules/mapnik
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/kosmtik/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding/node-v51-linux-x64/mapnik.node --module_name=mapnik --module_path=/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/kosmtik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-57-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/kosmtik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/kosmtik/node_modules/mapnik
node-pre-gyp ERR! node -v v7.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/kosmtik/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding/node-v51-linux-x64/mapnik.node --module_name=mapnik --module_path=/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding/node-v51-linux-x64' (1)
/usr/local/lib
└── (empty)

npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "kosmtik"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! mapnik@3.5.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapnik@3.5.14 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/osm/npm-debug.log
```
Thanks for helping

**Comment by nebulon42** [comment]
node-mapnik is not yet compatible with Node 7. You seem to have two different versions of Node on your system? The one you listed with `nodejs -v`, which is v4.2.6 and another one which is v7.4.0.

See these lines in your output:
`node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.14 and node@7.4.0 (node-v51 ABI) (falling back to source compile with node-gyp)`
`node-pre-gyp ERR! node -v v7.4.0`

Make sure to remove the v7.4.0 version of Node.js and use v4 or v6 instead. You could also use nvm (https://github.com/creationix/nvm) to help you manage your node versions.

**Comment by MaelREBOUX** [comment]
Mmhh :
```bash
# nodejs -v
v4.2.6

wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash

npm ls -G --depth=0
/home/osm
├── @mapbox/carto@0.16.3
└── nvm@0.0.4
```

**Comment by MaelREBOUX** [comment]
Now that it is (maybe) clean, it is better but I still have an error because of the version of @mapbox/carto or mapnik@3.5.14 ?

```bash
# as root
apt-get install nodejs npm

nodejs -v
v4.2.6

find / -name "nodejs"
/usr/bin/nodejs
/usr/share/doc/nodejs
/usr/share/nodejs
/usr/share/lintian/overrides/nodejs
/usr/include/nodejs
/usr/lib/nodejs

npm install -g npm-check-updates

cd /usr/local/lib
npm ls -G --depth=0
/usr/local/lib
├── abbrev@1.0.9
├── aproba@1.0.4
├── asap@2.0.5
├── config-chain@1.1.11
├── fstream@1.0.10
├── fstream-npm@1.2.0
├── glob@7.1.0
├── graceful-fs@4.1.9
├── has-unicode@2.0.1
├── inherits@2.0.3
├── lockfile@1.0.2
├── lodash.clonedeep@4.5.0
├── lodash.union@4.6.0
├── lodash.uniq@4.5.0
├── lodash.without@4.4.0
├── minimatch@3.0.3
├── node-gyp@3.4.0
├── npm-check-updates@2.8.9
├── npm-package-arg@4.2.0
├── npm-registry-client@7.2.1
├── npm-user-validate@0.1.5
├── npmlog@4.0.0
├── once@1.4.0
├── opener@1.4.2
├── path-is-inside@1.0.2
├── read-package-tree@5.1.5
├── readable-stream@2.1.5
├── request@2.75.0
├── retry@0.10.0
├── rimraf@2.5.4
├── semver@5.3.0
├── sorted-object@2.0.1
├── which@1.2.11
├── wrappy@1.0.2
└── write-file-atomic@1.2.0

npm install -g @mapbox/carto
/usr/local/bin/carto -> /usr/local/lib/node_modules/@mapbox/carto/bin/carto
/usr/local/lib
└─┬ @mapbox/carto@0.16.3 

npm -g install kosmtik
npm WARN deprecated carto@0.15.3: This module is now under the @mapbox namespace: install @mapbox/carto instead
npm WARN lifecycle mapnik@3.5.14~preinstall: cannot run in wd %s %s (wd=%s) mapnik@3.5.14 npm install node-pre-gyp /usr/local/lib/node_modules/.staging/mapnik-b95e22e5

> mapnik@3.5.14 install /usr/local/lib/node_modules/kosmtik/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

/usr/bin/env: ‘node’: No such file or directory
/usr/local/lib
└── (empty)

npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "-g" "install" "kosmtik"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! mapnik@3.5.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the mapnik@3.5.14 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/npm-debug.log
npm ERR! code 1
```

**Comment by MaelREBOUX** [comment]
@nebulon42 thanks to re-open

**Comment by nebulon42** [comment]
You can ignore the warning about `@mapbox/carto` for now. Just a name change.
It is weird that your node.js is available as `nodejs`. node-mapnik somehow expects it to be `node` as in line `/usr/bin/env: ‘node’: No such file or directory`.

I'm on 16.04 myself but I have installed node.js from https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions. Maybe this would work for you?

I'm leaving this closed as it is not a problem with Kosmtik but with your environment, but I'm still happy to help you resolving your problems.

**Comment by MaelREBOUX** [comment]
One must do this to install a version 6 of Node.js

```bash
# as root
# https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
 
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
apt-get install -y nodejs
 
nodejs -v
v6.9.4
 
find / -name "nodejs"
/usr/bin/nodejs
/usr/share/doc/nodejs
/usr/share/nodejs
/usr/include/nodejs
/usr/lib/nodejs
 
cd /usr/local/lib/
```

Do the install

```bash
npm install -g npm-check-updates
 
npm ls -G --depth=0
/usr/local/lib
└── npm-check-updates@2.8.9
 
npm install -g @mapbox/carto

npm -g install kosmtik
npm WARN deprecated carto@0.15.3: This module is now under the @mapbox namespace: install @mapbox/carto instead
npm WARN lifecycle mapnik@3.5.14~preinstall: cannot run in wd %s %s (wd=%s) mapnik@3.5.14 npm install node-pre-gyp /usr/lib/node_modules/.staging/mapnik-216d48b0
 
> mapnik@3.5.14 install /usr/lib/node_modules/kosmtik/node_modules/mapnik
> node-pre-gyp install --fallback-to-build
 
[mapnik] Success: "/usr/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding/node-v48-linux-x64/mapnik.node" is installed via remote
/usr/lib
└─┬ kosmtik@0.0.13 
  ├─┬ carto@0.15.3 
  │ ├── mapnik-reference@8.5.6 
```

But kosmtik is not showned in the list of the modules ?

```bash
npm ls -G --depth=0
/usr/local/lib
├── @mapbox/carto@0.16.3
└── npm-check-updates@2.8.9
```

And no answer in the bash :
```bash
kosmtik
bash: kosmtik: command not found
```
A path variables issue ?

**Comment by MaelREBOUX** [comment]
ok : several 'node_modules' folders created by previous Node.js version.

All is now in /usr/lib/node_modules/

usr/lib/node_modules# npm ls -G --depth=0
/usr/lib
├── kosmtik@0.0.13
├── npm@3.10.10
└── npm-check-updates@2.8.9

But no more kosmtik in bash 

kosmtik
bash: kosmtik: command not found

**Comment by MaelREBOUX** [comment]
> You can ignore the warning about @mapbox/carto for now.

yes : understanded : it is just a warn

> I'm leaving this closed as it is not a problem with Kosmtik but with your environment, but I'm still happy to help you resolving your problems.

Sure ! I use a fresh Ubuntu 16.04.1 and I just found that we have to install a v6 of Node.js therefore Ubuntu with standard repo comes with v4… Hope it could help other users.

And thanks for re-opening.

**Comment by MaelREBOUX** [comment]
```bash
kosmtik
bash: kosmtik: command not found
```

Why there is no **bin** folder in the kosmtik folder ?
There is one for npm and npm-check-updates

**Comment by MaelREBOUX** [comment]
> This will create a node_modules/kosmtik folder. You then have to replace all occurences of kosmtik below with node node_modules/kosmtik/index.js.

Okkaayyy !
So we have to type **node /usr/lib/node_modules/kosmtik/index.js** and not **kosmtik** ! This is truely not clear in the README. I understand this by reading #207 

If we have to always type *node node_modules/kosmtik/index.js* for using kosmtik why write *kosmtik* ?

**Comment by nebulon42** [comment]
That should not be the case. The kosmtik command should be available in your shell. Also it should work with node v4. I will setup a fresh VM when I have the time and investigate.

**Comment by MaelREBOUX** [comment]
I'll do the same.

I propose to :
- close this issue
- open a new issue for this alias bash issue

Your opinion ?

**Comment by nebulon42** [comment]
Fine for me. :)

**Comment by MaelREBOUX** [comment]
#217
