### ISSUE TITLE
Error with the Test project

### ISSUE THREAD

**Issue by MaelREBOUX** [kosmtik/kosmtik#213]
I'm running kosmtik@0.0.13 on ubuntu 16.04.

I want to run  / serve the test project to check if all is correctly installed.
But : 

```
node /usr/lib/node_modules/kosmtik/index.js serve /usr/lib/node_modules/kosmtik/test/config.yml
[Core] No usable config file found in /home/osm/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading project from /usr/lib/node_modules/kosmtik/test/config.yml
/usr/lib/node_modules/kosmtik/src/back/loader/Base.js:10
    this.mml.metatile = +(this.mml.metatile || this.mml.source ? 1 : 2);  // Default vectortiles to 1, classic to 2.
                                  ^
TypeError: Cannot read property 'metatile' of undefined
    at Loader.BaseLoader.postprocess (/usr/lib/node_modules/kosmtik/src/back/loader/Base.js:10:35)
    at Loader.BaseLoader.load (/usr/lib/node_modules/kosmtik/src/back/loader/Base.js:75:10)
    at Project.load (/usr/lib/node_modules/kosmtik/src/back/Project.js:37:23)
    at new ProjectServer (/usr/lib/node_modules/kosmtik/src/back/ProjectServer.js:30:18)
    at PreviewServer.registerProject (/usr/lib/node_modules/kosmtik/src/back/PreviewServer.js:51:33)
    at PreviewServer.listen (/usr/lib/node_modules/kosmtik/src/back/PreviewServer.js:42:14)
    at emitNone (events.js:86:13)
    at Config.emit (events.js:185:7)
    at Config.parseOptions (/usr/lib/node_modules/kosmtik/src/Config.js:134:10)
    at Object.<anonymous> (/usr/lib/node_modules/kosmtik/index.js:10:8)
```

**Comment by nebulon42** [comment]
Sorry for the late answer. The `test` directory contains files for Kosmtik tests that are run with `npm test`. It is not a test project you could use to render something.
