### ISSUE TITLE
Works only on http://localhost:6789/ ? (how to access when running in a CLI only VM ?)

### ISSUE THREAD

**Issue by MaelREBOUX** [kosmtik/kosmtik#214]
I have a VM running Ubuntu 16.04. network is set to NAT.
It seems that kosmtik only answers on localhost because

1/ at kosmtik start :
```[Core] PreviewServer started, you can browse http://127.0.0.1:6789```

2/ when trying to access from my computer on its IP or local name :
```
wget --spider http://192.168.0.42:6789/
Spider mode enabled. Check if remote file exists.
--2017-01-10 00:03:39--  http://192.168.0.42:6789/
Connecting to 192.168.0.42:6789... failed: Connection refused.
```

The same logged in on the VM 
```
 wget --spider http://localhost:6789/osmorg/
Spider mode enabled. Check if remote file exists.
--2017-01-09 23:56:50--  http://localhost:6789/osmorg/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:6789... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:6789... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1338 (1.3K) [text/html]
Remote file exists and could contain further links,
but recursion is disabled -- not retrieving.
```
I could get the index.html file by another wget request.

How to access kosmtik from the network ?

I think about to set up a rewrite rule for the vhost in apache. Correct ?

**Comment by pnorman** [comment]
Use --host to specify a different host (e.g. 0.0.0.0)

**Comment by MaelREBOUX** [comment]
OK : seen that : https://github.com/kosmtik/kosmtik/commit/dcd58cf2a8c30e037b8bacce907b9a08fd87426d

--host and --port options

launched but…

```bash
node /usr/lib/node_modules/kosmtik/index.js serve /data/osm/styles/osmbr-mapstyle/project.mml --host 192.168.0.42
[Core] No usable config file found in /home/osm/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading project from /data/osm/styles/osmbr-mapstyle/project.mml
[Core] PreviewServer started, you can browse http://192.168.0.42:6789
(node:3972) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
[Local Config] Unable to load local config from /data/osm/styles/osmbr-mapstyle/localconfig.js
TypeError: (intermediate value).LocalConfig is not a function
    at Project.LocalConfig.patchMML (/usr/lib/node_modules/kosmtik/src/plugins/local-config/index.js:37:35)
    at Project.<anonymous> (/usr/lib/node_modules/kosmtik/src/back/StateBase.js:35:74)
    at /usr/lib/node_modules/kosmtik/src/back/Project.js:116:19
    at /usr/lib/node_modules/kosmtik/src/back/Utils.js:10:18
    at FSReqWrap.oncomplete (fs.js:123:15)
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.0.0
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
[httpserver] / 302
[httpserver] /osmbr-mapstyle 302
[httpserver] /osmbr-mapstyle/ 200
[httpserver] /node_modules/leaflet/dist/leaflet-src.js 200
[httpserver] /config/ 200
[httpserver] /osmbr-mapstyle/config/ 200
[httpserver] /node_modules/leaflet-formbuilder/Leaflet.FormBuilder.js 200
[httpserver] /src/front/Core.js 200
[httpserver] /src/front/Autocomplete.js 200
[httpserver] /src/front/DataInspector.js 200
[httpserver] /src/front/MetatilesBounds.js 200
[httpserver] /src/front/Sidebar.js 200
[httpserver] /src/front/Toolbar.js 200
[httpserver] /src/front/FormBuilder.js 200
[httpserver] /src/front/Settings.js 200
[httpserver] /src/front/Command.js 200

/usr/lib/node_modules/kosmtik/src/back/PreviewServer.js:141
    if (anonymous.name) throw 'Cannot use bridge helper with named function:' + anonymous.name;
                        ^
Cannot use bridge helper with named function:front
```

**Comment by MaelREBOUX** [comment]
to be continued: #216
