### ISSUE TITLE
PreviewServer.js : 'Cannot use bridge helper with named function:' + anonymous.name;

### ISSUE THREAD

**Issue by MaelREBOUX** [kosmtik/kosmtik#216]
I tried to launch a fork of osmlyrk mapstyle.
I set up a localconfig.js file

```bash
node /usr/lib/node_modules/kosmtik/index.js serve /data/osm/styles/osmbr-mapstyle/project.mml --host 192.168.0.42
[Core] No usable config file found in /home/osm/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading project from /data/osm/styles/osmbr-mapstyle/project.mml
[Core] PreviewServer started, you can browse http://192.168.0.42:6789
(node:3972) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
[Local Config] Unable to load local config from /data/osm/styles/osmbr-mapstyle/localconfig.js
TypeError: (intermediate value).LocalConfig is not a function
    at Project.LocalConfig.patchMML (/usr/lib/node_modules/kosmtik/src/plugins/local-config/index.js:37:35)
    at Project.<anonymous> (/usr/lib/node_modules/kosmtik/src/back/StateBase.js:35:74)
    at /usr/lib/node_modules/kosmtik/src/back/Project.js:116:19
    at /usr/lib/node_modules/kosmtik/src/back/Utils.js:10:18
    at FSReqWrap.oncomplete (fs.js:123:15)
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.0.0
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
[httpserver] / 302
[httpserver] /osmbr-mapstyle 302
[httpserver] /osmbr-mapstyle/ 200
[httpserver] /node_modules/leaflet/dist/leaflet-src.js 200
[httpserver] /config/ 200
[httpserver] /osmbr-mapstyle/config/ 200
[httpserver] /node_modules/leaflet-formbuilder/Leaflet.FormBuilder.js 200
[httpserver] /src/front/Core.js 200
[httpserver] /src/front/Autocomplete.js 200
[httpserver] /src/front/DataInspector.js 200
[httpserver] /src/front/MetatilesBounds.js 200
[httpserver] /src/front/Sidebar.js 200
[httpserver] /src/front/Toolbar.js 200
[httpserver] /src/front/FormBuilder.js 200
[httpserver] /src/front/Settings.js 200
[httpserver] /src/front/Command.js 200

/usr/lib/node_modules/kosmtik/src/back/PreviewServer.js:141
    if (anonymous.name) throw 'Cannot use bridge helper with named function:' + anonymous.name;
                        ^
Cannot use bridge helper with named function:front
```

**Comment by yohanboniface** [comment]
> (node:3972) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'

Seems you don't have trunk version, do you?

**Comment by MaelREBOUX** [comment]
```
cd /usr/lib/
root@osm-ubuntu:/usr/lib# npm ls -G --depth=0
/usr/lib
├── kosmtik@0.0.13
├── npm@3.10.10
└── npm-check-updates@2.8.9
```

**Comment by yohanboniface** [comment]
Oh, wow, 0.0.13 is more than one year old. We need a new release. 

@nebulon42 anything in the air we should wait for releasing or should I go?

**Comment by MaelREBOUX** [comment]
ok. so quickly I think I have to git clone then run npm install ?

**Comment by yohanboniface** [comment]
For now, yes

**Comment by MaelREBOUX** [comment]
```
cd /data/osm/
git clone https://github.com/kosmtik/kosmtik.git
cd kosmtik
npm install

> mapnik@3.5.14 preinstall /data/osm/kosmtik/node_modules/.staging/mapnik-f2c68c53
> npm install node-pre-gyp

(...)

npm ls -G --depth=0
kosmtik@0.0.13 /data/osm/kosmtik
├── @mapbox/carto@0.16.3
├── generic-pool@3.1.6
├── js-yaml@3.7.0
├── json-localizer@0.0.3
├── leaflet@1.0.2
├── leaflet-formbuilder@0.2.3
├── leaflet-hash@0.2.1
├── mapnik@3.5.14
├── mocha@3.2.0
├── node-pre-gyp@0.6.32 extraneous
├── nomnom@1.8.1
├── npm@4.0.5
├── request@2.79.0
└── semver@5.3.0

npm ERR! extraneous: node-pre-gyp@0.6.32 /data/osm/kosmtik/node_modules/node-pre-gyp
```
It is again a v 0.0.13 ?!

**Comment by yohanboniface** [comment]
> It is again a v 0.0.13 ?!

Sure, without a release, the version is not bumped. But the code is up to date.

**Comment by MaelREBOUX** [comment]
Better :

```
node /data/osm/kosmtik/index.js -h
[Core] No usable config file found in /home/osm/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js

Usage: /usr/bin/nodejs index.js <command> [options]

command     
  serve       Run the server
  plugins     Manage plugins
  export      Export a project

Options:
   --port             Port to listen on.  [6789]
   --host             Host to listen on.  [127.0.0.1]
   --mapnik-version   Optional mapnik reference version to be passed to Carto  [3.0.12]
   --proxy            Optional proxy to use when doing http requests
   --keep-cache       Do not flush cached metatiles on project load
   --renderer         Specify a renderer by its name, carto is the default.  [carto]
   --metatile         Override mml metatile setting [Default: mml setting]
   --localconfig      Path to local config file [Default: {projectpath}/localconfig.json|.js]
```
And we can see the host option :D

Let's try

```
node /data/osm/kosmtik/index.js serve /data/osm/styles/osmbr-mapstyle/project.mml --host 192.168.0.42
[Core] No usable config file found in /home/osm/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading project from /data/osm/styles/osmbr-mapstyle/project.mml
[Core] PreviewServer started, you can browse http://192.168.0.42:6789
[Core] Creating metatiles cache dir tmp/osmbr-mapstyle/meta
[Core] Deleting previous metatiles tmp/osmbr-mapstyle/meta
[Core] Created vector cache dir tmp/osmbr-mapstyle/vector
[Local Config] Unable to load local config from /data/osm/styles/osmbr-mapstyle/localconfig.js
TypeError: (intermediate value).LocalConfig is not a function
    at Project.LocalConfig.patchMML (/data/osm/kosmtik/src/plugins/local-config/index.js:37:35)
    at Project.<anonymous> (/data/osm/kosmtik/src/back/StateBase.js:35:74)
    at PluginsManager.handleProject (/data/osm/kosmtik/src/back/PluginsManager.js:173:15)
    at Project.<anonymous> (/data/osm/kosmtik/src/back/StateBase.js:35:74)
    at /data/osm/kosmtik/src/back/Project.js:141:19
    at /data/osm/kosmtik/src/back/Utils.js:10:18
    at FSReqWrap.oncomplete (fs.js:123:15)
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.0.12
Warning: using the name attribute for layers (like background here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like land here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like processed_p here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like shoreline_300 here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like landuse_gen0 here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like landuse_gen1 here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like out here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like 2kmTM here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like landuse here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like hillshading here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like waterway_low here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like waterway_med here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like waterway_high here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like naturalearth here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like water_gen0 here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like water_gen1 here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like water here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like landuse_overlays here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like buildings here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like aeroway here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like tunnel here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like turning_circle_case here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like roads_high here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like roads_med here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like roads_low here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like rail_low here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like turning_circle_fill here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like bridge here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like admin here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like bundeslaender here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like landesgrenzen here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like place here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like motorway_label here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like mainroad_label here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like minorroad_label here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like waterway_label here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like housenumber here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like addrinterpolation here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like laender_abk here) is deprecated and will be removed in 1.0.0. Use id instead.
[Core] Loading map…
Class constructor Pool cannot be invoked without 'new'
[httpserver] /osmbr-mapstyle/poll/ 200
[httpserver] /osmbr-mapstyle/ 200
[httpserver] /src/plugins/base-exporters/front/export.js 200
[httpserver] /hash.js 200
[httpserver] /node_modules/leaflet/dist/leaflet.css 200
[httpserver] /src/front/Sidebar.css 200
[httpserver] /src/front/Toolbar.css 200
[httpserver] /src/front/Core.css 200
[httpserver] /config/ 200
[httpserver] /osmbr-mapstyle/config/ 200
[httpserver] /node_modules/leaflet/dist/leaflet-src.js 200
[httpserver] /node_modules/leaflet-formbuilder/Leaflet.FormBuilder.js 200
[httpserver] /src/front/Core.js 200
[httpserver] /src/front/Autocomplete.js 200
[httpserver] /src/front/DataInspector.js 200
[httpserver] /src/front/MetatilesBounds.js 200
[httpserver] /src/front/Sidebar.js 200
[httpserver] /src/front/Toolbar.js 200
[httpserver] /src/front/FormBuilder.js 200
[httpserver] /src/front/Settings.js 200
[httpserver] /src/front/Command.js 200
[httpserver] /src/front/Map.js 200
[httpserver] /node_modules/leaflet-hash/leaflet-hash.js 200
[httpserver] /src/front/header_logo.svg 200
[httpserver] /src/front/fonts/FiraSans-Light.woff 200
[httpserver] /src/front/fonts/DejaVuSans-webfont.woff 200
Trace
    at ProjectServer.raise (/data/osm/kosmtik/src/back/ProjectServer.js:257:13)
    at ProjectServer.serveTile (/data/osm/kosmtik/src/back/ProjectServer.js:63:14)
    at tile (/data/osm/kosmtik/src/back/ProjectServer.js:46:108)
    at Project.StateBase.when (/data/osm/kosmtik/src/back/StateBase.js:51:33)
    at ProjectServer.serve (/data/osm/kosmtik/src/back/ProjectServer.js:46:70)
    at PreviewServer.forwardToProject (/data/osm/kosmtik/src/back/PreviewServer.js:74:23)
    at PreviewServer.serve (/data/osm/kosmtik/src/back/PreviewServer.js:68:42)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
Project not loaded properly.
[httpserver] /osmbr-mapstyle/tile/10/551/342.png?t=1484020588682 500
Trace
    at ProjectServer.raise (/data/osm/kosmtik/src/back/ProjectServer.js:257:13)
    at ProjectServer.serveTile (/data/osm/kosmtik/src/back/ProjectServer.js:63:14)
    at tile (/data/osm/kosmtik/src/back/ProjectServer.js:46:108)
    at Project.StateBase.when (/data/osm/kosmtik/src/back/StateBase.js:51:33)
    at ProjectServer.serve (/data/osm/kosmtik/src/back/ProjectServer.js:46:70)
    at PreviewServer.forwardToProject (/data/osm/kosmtik/src/back/PreviewServer.js:74:23)
    at PreviewServer.serve (/data/osm/kosmtik/src/back/PreviewServer.js:68:42)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
Project not loaded properly.
```

This seems functionnal.

**Comment by nebulon42** [comment]
@yohanboniface Yes, please do a release. :)
