### ISSUE TITLE
Class constructors cannot be invoked without 'new'

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#219]
```
pnorman@pippin:~/osm/brighmed$ rm -rf tmp/ && ~/osm/kosmtik/index.js serve --host 192.168.1.1 project.yml
[Core] Loading config from /home/pnorman/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading plugin from kosmtik-map-compare
[Core] Loading project from project.yml
[Core] PreviewServer started, you can browse http://192.168.1.1:6789
[Core] Creating metatiles cache dir tmp/brighmed/meta
[Core] Deleting previous metatiles tmp/brighmed/meta
[Core] Created vector cache dir tmp/brighmed/vector
[Local Config] Patched config from /home/pnorman/osm/brighmed/localconfig.json
[datasource loader] Loading source from /home/pnorman/osm/meddo
[Core] Loading project from /home/pnorman/osm/meddo/data.yml
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.0.12
Warning: using the name attribute for layers (like park here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like landcover here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like waterway here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like water here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like building here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like transport here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like boundary here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like place here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like transport_name here) is deprecated and will be removed in 1.0.0. Use id instead.
[Core] Loading map…
Class constructors cannot be invoked without 'new'
[httpserver] /brighmed/poll/ 200
[Core] Creating metatiles cache dir tmp/meddo/meta
[Core] Deleting previous metatiles tmp/meddo/meta
[Core] Created vector cache dir tmp/meddo/vector
[Local Config] Unable to load local config from /home/pnorman/osm/meddo/localconfig.js
[Error: File not found: /home/pnorman/osm/meddo/localconfig.js]
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.0.12
Warning: using the name attribute for layers (like water here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like waterway here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like waterway_name here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like boundary here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like park here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like building here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like transport here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like transport_name here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like place here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like landcover here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like landuse here) is deprecated and will be removed in 1.0.0. Use id instead.
[Core] Loading map…
Class constructors cannot be invoked without 'new'
```

When i try to load the page I get

```
Trace
    at ProjectServer.raise (/home/pnorman/osm/kosmtik/src/back/ProjectServer.js:257:13)
    at ProjectServer.serveTile (/home/pnorman/osm/kosmtik/src/back/ProjectServer.js:63:14)
    at tile (/home/pnorman/osm/kosmtik/src/back/ProjectServer.js:46:108)
    at StateBase.when (/home/pnorman/osm/kosmtik/src/back/StateBase.js:51:33)
    at ProjectServer.serve (/home/pnorman/osm/kosmtik/src/back/ProjectServer.js:46:70)
    at PreviewServer.forwardToProject (/home/pnorman/osm/kosmtik/src/back/PreviewServer.js:74:23)
    at PreviewServer.serve (/home/pnorman/osm/kosmtik/src/back/PreviewServer.js:68:42)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:536:12)
Project not loaded properly.
[httpserver] /brighmed/tile/12/648/1403.png?t=1484259578905 500
```

**Comment by pnorman** [comment]
`git bisect` tells me the offending commit is 998e5fd21a16f014e8e62546de0b7c89ce0fd7ce, and trying to manually split that apart makes me think it's generic-pool.

https://gist.github.com/sandfox/5ca20648b60a0cb959638c0cd6fcd02d might be relevant.
