### ISSUE TITLE
New Install: Cannot use bridge helper with named function:front

### ISSUE THREAD

**Issue by csytsma** [kosmtik/kosmtik#223]
I'm attempting to install kosmtik for the first time.  Followed the installation instructions.  Appeared to install correctly.  Trying to open an existing Tilemill .mml project file, and get the following error when opening the browser window:
```
[httpserver] /node_modules/leaflet-formbuilder/Leaflet.FormBuilder.js 200

/usr/local/lib/node_modules/kosmtik/src/back/PreviewServer.js:141
    if (anonymous.name) throw 'Cannot use bridge helper with named function:' + anonymous.name;
                        ^
Cannot use bridge helper with named function:front
```
Output when starting:

```
$ kosmtik serve /Users/<username>/Google\ Drive/MapBox/project/Teanaway/project.mml
[Core] No usable config file found in /Users/<username>/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading project from /Users/<username>/Google Drive/MapBox/project/Teanaway/project.mml
[Core] PreviewServer started, you can browse http://127.0.0.1:6789
(node:67407) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
[Local Config] Unable to load local config from /Users/<username>/Google Drive/MapBox/project/Teanaway/localconfig.js
Error: File not found: /Users/<username>/Google Drive/MapBox/project/Teanaway/localconfig.js
    at Project.LocalConfig.patchMML (/usr/local/lib/node_modules/kosmtik/src/plugins/local-config/index.js:30:15)
    at Project.<anonymous> (/usr/local/lib/node_modules/kosmtik/src/back/StateBase.js:35:74)
    at /usr/local/lib/node_modules/kosmtik/src/back/Project.js:116:19
    at /usr/local/lib/node_modules/kosmtik/src/back/Utils.js:10:18
    at FSReqWrap.oncomplete (fs.js:123:15)
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.0.0
```

I'm assuming I'm doing something wrong?

**Comment by yohanboniface** [comment]
Please install from github master for now. NPM needs a new release. Will do asap.

**Comment by nebulon42** [comment]
@yohanboniface A new release is really needed. Please give me publish rights on NPM too. Thanks.

**Comment by yohanboniface** [comment]
Done!
Sorry for the lag, was offline.
Added you also as kosmtik maintainer on npm.
Thought about creating an organization, but it needs $$.
