### ISSUE TITLE
currently can't install due to mapnik build failure?

### ISSUE THREAD

**Issue by robshep** [kosmtik/kosmtik#226]
I assume this is just an upstream error.  Any suggestions however?

OS X Sierra 10.12.2 with NVM providing....

```
$ node -v
v7.5.0
$ npm -v
4.1.2
```

trying this

```
$ npm install kosmtik
```

shows...
```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.14 and node@7.5.0 (node-v51 ABI) (falling back to source compile with node-gyp)
/bin/sh: mapnik-config: command not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
```

Full trace below.

```
rob$ npm install kosmtik

> mapnik@3.5.14 preinstall /Users/rob/Projects/mapsProj/node_modules/.staging/mapnik-8aeebae0
> npm install node-pre-gyp

mapnik@3.5.14 /Users/rob/Projects/mapsProj/node_modules/.staging/mapnik-8aeebae0
└─┬ node-pre-gyp@0.6.33
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├─┬ nopt@3.0.6
  │ └── abbrev@1.0.9
  ├─┬ npmlog@4.0.2
  │ ├─┬ are-we-there-yet@1.1.2
  │ │ ├── delegates@1.0.0
  │ │ └── readable-stream@2.2.2
  │ ├── console-control-strings@1.1.0
  │ ├─┬ gauge@2.7.2
  │ │ ├── aproba@1.0.4
  │ │ ├── has-unicode@2.0.1
  │ │ ├── object-assign@4.1.1
  │ │ ├── signal-exit@3.0.2
  │ │ ├─┬ string-width@1.0.2
  │ │ │ ├── code-point-at@1.1.0
  │ │ │ └─┬ is-fullwidth-code-point@1.0.0
  │ │ │   └── number-is-nan@1.0.1
  │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ └── ansi-regex@2.1.1
  │ │ ├── supports-color@0.2.0
  │ │ └── wide-align@1.1.0
  │ └── set-blocking@2.0.0
  ├─┬ rc@1.1.6
  │ ├── deep-extend@0.4.1
  │ ├── ini@1.3.4
  │ ├── minimist@1.2.0
  │ └── strip-json-comments@1.0.4
  ├─┬ request@2.79.0
  │ ├── aws-sign2@0.6.0
  │ ├── aws4@1.5.0
  │ ├── caseless@0.11.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.0
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@2.1.2
  │ │ └── asynckit@0.4.0
  │ ├─┬ har-validator@2.0.6
  │ │ ├─┬ chalk@1.1.3
  │ │ │ ├── ansi-styles@2.2.1
  │ │ │ ├── escape-string-regexp@1.0.5
  │ │ │ ├── has-ansi@2.0.0
  │ │ │ └── supports-color@2.0.0
  │ │ ├─┬ commander@2.9.0
  │ │ │ └── graceful-readlink@1.0.1
  │ │ ├─┬ is-my-json-valid@2.15.0
  │ │ │ ├── generate-function@2.0.0
  │ │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ │ └── is-property@1.0.2
  │ │ │ ├── jsonpointer@4.0.1
  │ │ │ └── xtend@4.0.1
  │ │ └─┬ pinkie-promise@2.0.1
  │ │   └── pinkie@2.0.4
  │ ├─┬ hawk@3.1.3
  │ │ ├── boom@2.10.1
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@1.1.1
  │ │ ├── assert-plus@0.2.0
  │ │ ├─┬ jsprim@1.3.1
  │ │ │ ├── extsprintf@1.0.2
  │ │ │ ├── json-schema@0.2.3
  │ │ │ └── verror@1.3.6
  │ │ └─┬ sshpk@1.10.2
  │ │   ├── asn1@0.2.3
  │ │   ├── assert-plus@1.0.0
  │ │   ├── bcrypt-pbkdf@1.0.1
  │ │   ├─┬ dashdash@1.14.1
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── ecc-jsbn@0.1.1
  │ │   ├─┬ getpass@0.1.6
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── jodid25519@1.0.2
  │ │   ├── jsbn@0.1.0
  │ │   └── tweetnacl@0.14.5
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.14
  │ │ └── mime-db@1.26.0
  │ ├── oauth-sign@0.8.2
  │ ├── qs@6.3.0
  │ ├── stringstream@0.0.5
  │ ├─┬ tough-cookie@2.3.2
  │ │ └── punycode@1.4.1
  │ ├── tunnel-agent@0.4.3
  │ └── uuid@3.0.1
  ├─┬ rimraf@2.5.4
  │ └─┬ glob@7.1.1
  │   ├── fs.realpath@1.0.0
  │   ├── inflight@1.0.6
  │   ├─┬ minimatch@3.0.3
  │   │ └─┬ brace-expansion@1.1.6
  │   │   ├── balanced-match@0.4.2
  │   │   └── concat-map@0.0.1
  │   ├── once@1.4.0
  │   └── path-is-absolute@1.0.1
  ├── semver@5.3.0
  ├─┬ tar@2.2.1
  │ ├── block-stream@0.0.9
  │ ├─┬ fstream@1.0.10
  │ │ └── graceful-fs@4.1.11
  │ └── inherits@2.0.3
  └─┬ tar-pack@3.3.0
    ├─┬ debug@2.2.0
    │ └── ms@0.7.1
    ├── fstream-ignore@1.0.5
    ├─┬ once@1.3.3
    │ └── wrappy@1.0.2
    ├─┬ readable-stream@2.1.5
    │ ├── buffer-shims@1.0.0
    │ ├── core-util-is@1.0.2
    │ ├── isarray@1.0.0
    │ ├── process-nextick-args@1.0.7
    │ ├── string_decoder@0.10.31
    │ └── util-deprecate@1.0.2
    └── uid-number@0.0.6

npm WARN mapnik@3.5.14 No license field.

> mapnik@3.5.14 install /Users/rob/Projects/mapsProj/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.14 and node@7.5.0 (node-v51 ABI) (falling back to source compile with node-gyp)
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
/bin/sh: mapnik-config: command not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/rob/Projects/mapsProj/node_modules/npm/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.3.0
gyp ERR! command "/Users/rob/.nvm/versions/node/v7.5.0/bin/node" "/Users/rob/Projects/mapsProj/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/rob/Projects/mapsProj/node_modules/mapnik/lib/binding/node-v51-darwin-x64/mapnik.node" "--module_name=mapnik" "--module_path=/Users/rob/Projects/mapsProj/node_modules/mapnik/lib/binding/node-v51-darwin-x64"
gyp ERR! cwd /Users/rob/Projects/mapsProj/node_modules/mapnik
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/rob/.nvm/versions/node/v7.5.0/bin/node /Users/rob/Projects/mapsProj/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/rob/Projects/mapsProj/node_modules/mapnik/lib/binding/node-v51-darwin-x64/mapnik.node --module_name=mapnik --module_path=/Users/rob/Projects/mapsProj/node_modules/mapnik/lib/binding/node-v51-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/rob/Projects/mapsProj/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:890:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.3.0
node-pre-gyp ERR! command "/Users/rob/.nvm/versions/node/v7.5.0/bin/node" "/Users/rob/Projects/mapsProj/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/rob/Projects/mapsProj/node_modules/mapnik
node-pre-gyp ERR! node -v v7.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok
Failed to execute '/Users/rob/.nvm/versions/node/v7.5.0/bin/node /Users/rob/Projects/mapsProj/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/rob/Projects/mapsProj/node_modules/mapnik/lib/binding/node-v51-darwin-x64/mapnik.node --module_name=mapnik --module_path=/Users/rob/Projects/mapsProj/node_modules/mapnik/lib/binding/node-v51-darwin-x64' (1)
npm WARN enoent ENOENT: no such file or directory, open '/Users/rob/Projects/mapsProj/package.json'
npm WARN mapsProj No description
npm WARN mapsProj No repository field.
npm WARN mapsProj No README data
npm WARN mapsProj No license field.
npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/rob/.nvm/versions/node/v7.5.0/bin/node" "/Users/rob/.nvm/versions/node/v7.5.0/bin/npm" "install" "kosmtik"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! mapnik@3.5.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@3.5.14 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rob/Projects/mapsProj/npm-debug.log
```

**Comment by robshep** [comment]
...Just realised I should probably be using node 6 LTS...

**Comment by robshep** [comment]
Yes, installs OK when running Node LTS 6.9.5, sorry
