### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#235]
```
[Core] Loading project from project.yml
[httpserver] /meddo/tile/7/66/46.pbf 200
[Core] Creating metatiles cache dir tmp/brighmed/meta
[Core] Deleting previous metatiles tmp/brighmed/meta
/home/pnorman/kosmtik/src/back/Utils.js:36
        return str.replace(/\{ *([\w_]+) *\}/g, function (str, key) {
                  ^

TypeError: Cannot read property 'replace' of undefined
    at Object.module.exports.template (/home/pnorman/kosmtik/src/back/Utils.js:36:19)
    at VectorBasedTile._render (/home/pnorman/kosmtik/src/back/VectorBasedTile.js:52:24)
    at VectorBasedTile.render (/home/pnorman/kosmtik/src/back/VectorBasedTile.js:112:10)
    at /home/pnorman/kosmtik/src/back/ProjectServer.js:74:21
    at dispense (/home/pnorman/kosmtik/node_modules/mapnik-pool/node_modules/generic-pool/lib/generic-pool.js:258:16)
    at Object.me.release (/home/pnorman/kosmtik/node_modules/mapnik-pool/node_modules/generic-pool/lib/generic-pool.js:368:5)
    at release (/home/pnorman/kosmtik/src/back/ProjectServer.js:70:49)
    at /home/pnorman/kosmtik/src/back/ProjectServer.js:81:17
Segmentation fault
```

**Comment by nebulon42** [comment]
There are two instance where `str` can be undefined:
* https://github.com/kosmtik/kosmtik/blob/6086c5ec1a03d9e668b0d9ac04aabb35a712eb18/src/back/VectorBasedTile.js#L52
* https://github.com/kosmtik/kosmtik/blob/b452b649783bcae3bcc6f880eccf797c40002e59/src/back/XRayTile.js#L39

**Comment by nebulon42** [comment]
Duplicate of #17?
