### ISSUE TITLE
optional arg 'scale' must be a number

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#241]
```
/home/pnorman/osm/kosmtik/src/back/Tile.js:34
    map.render(im, {scale: project.mml.scale, variables: {zoom: this.z}}, cb);
        ^

TypeError: optional arg 'scale' must be a number
    at TypeError (native)
    at Tile.render (/home/pnorman/osm/kosmtik/src/back/Tile.js:34:9)
    at MetatileBasedTile.renderMetatile (/home/pnorman/osm/kosmtik/src/back/MetatileBasedTile.js:73:10)
    at /home/pnorman/osm/kosmtik/src/back/MetatileBasedTile.js:44:26
    at /home/pnorman/osm/kosmtik/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/pnorman/osm/kosmtik/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
Segmentation fault
```

Scale does not appear in the MML file

**Comment by nebulon42** [comment]
A default for `project.mml.scale` has to be set.
