### ISSUE TITLE
Error generating MBTiles file

### ISSUE THREAD

**Issue by RandyHBH** [kosmtik/kosmtik#258]
Hi, I dont know if this is the right place to ask this but i am Running OpenStreetMap Carto with Docker and when trying to export mbtiles give me this error, if anyone could help me with this.

```
/usr/lib/node_modules/kosmtik/src/Config.js:73
        if (err.code !== 'EEXIST') throw err;
                                   ^
Error: EACCES: permission denied, mkdir '/.config'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:924:18)
    at Config.ensureDefaultUserConfigPath (/usr/lib/node_modules/kosmtik/src/Config.js:71:12)
    at new Config (/usr/lib/node_modules/kosmtik/src/Config.js:24:32)
    at Object.<anonymous> (/usr/lib/node_modules/kosmtik/index.js:8:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by d3netxer** [comment]
I got this error because I didn't log into my Docker container as the correct user with the correct permissions. 

This is how I was able to run the kosmtik command inside of the running container:

1st: In the 'scripts/docker-startup.sh' file I commented out the line kosmtik serve project.mml --host 0.0.0.0 because I didn't want the kosmtik server already up when I entered the running container. Then I added this line tail -f /dev/null so that the container would keep on running when I used the docker-compose up kosmtik command

2nd: I logged in the the server using another terminal and entered the container as the root user: ```sudo docker exec -u 0 -it containerID /bin/bash```

Then once in the container I was able to run kosmtik commands.

However, I myself am not able to export mbtiles, even though I would like to.
