### ISSUE TITLE
"Project not loaded properly" errors

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#263]
When loading a project with a CartoCSS error it's common to get the error

```
[httpserver] /repo/tile/16/10387/22445.png?t=1505811097827 500
Trace
    at ProjectServer.raise (/home/pnorman/osm/kosmtik/src/back/ProjectServer.js:257:13)
    at ProjectServer.serveTile (/home/pnorman/osm/kosmtik/src/back/ProjectServer.js:63:14)
    at tile (/home/pnorman/osm/kosmtik/src/back/ProjectServer.js:46:108)
    at StateBase.when (/home/pnorman/osm/kosmtik/src/back/StateBase.js:51:33)
    at ProjectServer.serve (/home/pnorman/osm/kosmtik/src/back/ProjectServer.js:46:70)
    at PreviewServer.forwardToProject (/home/pnorman/osm/kosmtik/src/back/PreviewServer.js:74:23)
    at PreviewServer.serve (/home/pnorman/osm/kosmtik/src/back/PreviewServer.js:68:42)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:539:12)
Project not loaded properly.
```

The carto binary can produce more detailed errors, e.g. 

```
$ ./node_modules/.bin/carto project.mml > /dev/null
Error: transportation.mss:408:23 variable @living-fill is undefined
    at Object.env.error (/home/pnorman/osm/openstreetmap-carto/repo/node_modules/carto/lib/carto/parser.js:249:55)
    at Object.tree.Variable.ev (/home/pnorman/osm/openstreetmap-carto/repo/node_modules/carto/lib/carto/tree/variable.js:23:17)
    at Object.tree.Expression.ev (/home/pnorman/osm/openstreetmap-carto/repo/node_modules/carto/lib/carto/tree/expression.js:15:34)
    at Object.tree.Value.ev (/home/pnorman/osm/openstreetmap-carto/repo/node_modules/carto/lib/carto/tree/value.js:11:34)
    at Rule.tree.Rule.ev (/home/pnorman/osm/openstreetmap-carto/repo/node_modules/carto/lib/carto/tree/rule.js:129:20)
    at Definition.tree.Definition.symbolizersToXML (/home/pnorman/osm/openstreetmap-carto/repo/node_modules/carto/lib/carto/tree/definition.js:142:42)
    at Definition.tree.Definition.toXML (/home/pnorman/osm/openstreetmap-carto/repo/node_modules/carto/lib/carto/tree/definition.js:218:33)
    at /home/pnorman/osm/openstreetmap-carto/repo/node_modules/carto/lib/carto/tree/style.js:40:27
    at Array.map (native)
    at Object.tree.StyleXML (/home/pnorman/osm/openstreetmap-carto/repo/node_modules/carto/lib/carto/tree/style.js:39:29)
```

It would be good to make these more detailed errors available from Kosmtik.

**Comment by yohanboniface** [comment]
The Carto error should be up in the console logs.

AFAIK, given the async nature of the code, it was a bit hard uggly to keep the original error somewhere available to read it when actually trying to make a tile. But I agree that the current situation is not user friendly.

**Comment by pnorman** [comment]
> The Carto error should be up in the console logs.

I couldn't find it, but won't rule it out. It's hard to see the errors because you see 10-40 of the error, one for each tile.

Could we display at the bottom like other errors?

**Comment by yohanboniface** [comment]
It's not simple: loading the project and building tiles are distinct, plus there are two scenarios, loading an invalid css (i.e. running `serve` with an invalid mss) or reloading after making the mss invalid (so basically from the browser).
In the first scenario, we could raise to prevent the project to run, which is the clearer message possible, but we don't want to raise when the project is reloaded from the browser.
On the other hand, we could display the error in the browser when reloading, but that would not work for the project run from the beginning with an invalid mss.

Anyway, I'll try to make that dance better.

**Comment by yohanboniface** [comment]
Ah, plus, when using "autoreload" (which I use myself), the project reloading is node made after any user action, so we don't have a callback hook at all. Gasp.

**Comment by yohanboniface** [comment]
Ah, when the project is running and you make the mss invalid, you'll have the message as expected, in the browser bottom notification area.

So I guess the scenario you were hitting is when running "server project.yml" with an invalid mss (vs the mss become invalid while the project is already running) ?

**Comment by pnorman** [comment]
> Ah, when the project is running and you make the mss invalid, you'll have the message as expected, in the browser bottom notification area.

No, I don't.
