### ISSUE TITLE
Kosmtik crashes with new master code

### ISSUE THREAD

**Issue by kocio-pl** [kosmtik/kosmtik#272]
After updating master tree and reinstalling plugins Kosmtik dies during starting phase:

```
[Core] Loading map…
[Core] Map ready
fs.js:1376
    throw error;
    ^

Error: watch style.mss ENOENT
    at _errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1374:19)
    at Object.fs.watch (fs.js:1400:11)
    at Array.<anonymous> (/media/hdd/home/kocio/devel/kosmtik/src/back/ProjectServer.js:32:16)
    at Project.<anonymous> (/media/hdd/home/kocio/devel/kosmtik/src/back/StateBase.js:27:43)
    at Project.<anonymous> (/media/hdd/home/kocio/devel/kosmtik/src/back/StateBase.js:37:13)
    at DataSourceLoader.patchMML (/media/hdd/home/kocio/devel/kosmtik/src/plugins/datasource-loader/index.js:51:15)
    at Project.<anonymous> (/media/hdd/home/kocio/devel/kosmtik/src/back/StateBase.js:35:74)
    at done (/media/hdd/home/kocio/devel/kosmtik/src/plugins/local-config/index.js:14:23)
    at Project.LocalConfig.patchMML (/media/hdd/home/kocio/devel/kosmtik/src/plugins/local-config/index.js:32:16)
```

**Comment by yohanboniface** [comment]
Which version of Node are you running?

**Comment by yohanboniface** [comment]
Seems it complains because "style.mss" does not exist on filesystem while it's referenced in the `Stylesheets` property.
I guess you are running openstreetmap-carto, so `style.mss` does exist, so it's certainly something else. But it's worth a check :)

**Comment by kocio-pl** [comment]
I was happily using v4.x packages from Ubuntu until now, but when I met this bug, I have installed current node.js LTS:
```
$ nodejs -v
v8.9.1
```
I have noticed that it shows just different number now (`fs.js:1376`, I don't remember what was it before), but the bug is the same.

I thought that it might be something about symlinks, but with freshly cloned osm-carto and no symlinks it's the same.

When I removed `- style.mss` line from project.mml, it complains about `fonts.mss` (next item on the list).

**Comment by yohanboniface** [comment]
Are you running kosmtik from the root of the openstreetmap-carto project or from elsewhere?

**Comment by kocio-pl** [comment]
I have found the working solution.

Until now I was making cd to kosmtik directory and run it as written in the README:

```node index.js serve <path/to/your/project.mml>```

but now I have to do the other way around - cd to project directory and then:

```node <path/to/kosmtik/index.js> serve project.mml```

So it seems to me that README needs to be corrected.

**Comment by yohanboniface** [comment]
I'll better fix the code so it can be ran from anywhere :)

**Comment by yohanboniface** [comment]
@kocio-pl can you update to latest commit and try again?

**Comment by kocio-pl** [comment]
Now it works as before, thanks a lot! :heart_eyes:
