### ISSUE TITLE
Cannot install kosmtik

### ISSUE THREAD

**Issue by Xeenych** [kosmtik/kosmtik#292]
I'm using 
npm -g install kosmtik

and the get this error:
```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v57-win32-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@8.12.0(node-v57 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files (x86)\Python37-32\python.
EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:336:11)

gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:561:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--f
allback-to-build" "--module=C:\\Users\\Tsvetik\\AppData\\Roaming\\npm\\node_modu
les\\kosmtik\\node_modules\\mapnik\\lib\\binding\\mapnik.node" "--module_name=ma
pnik" "--module_path=C:\\Users\\Tsvetik\\AppData\\Roaming\\npm\\node_modules\\ko
smtik\\node_modules\\mapnik\\lib\\binding"
gyp ERR! cwd C:\Users\Tsvetik\AppData\Roaming\npm\node_modules\kosmtik\node_modu
les\mapnik
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.j
s configure --fallback-to-build --module=C:\Users\Tsvetik\AppData\Roaming\npm\no
de_modules\kosmtik\node_modules\mapnik\lib\binding\mapnik.node --module_name=map
nik --module_path=C:\Users\Tsvetik\AppData\Roaming\npm\node_modules\kosmtik\node
_modules\mapnik\lib\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Tsvetik\AppDat
a\Roaming\npm\node_modules\kosmtik\node_modules\mapnik\node_modules\node-pre-gyp
\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Tsve
tik\\AppData\\Roaming\\npm\\node_modules\\kosmtik\\node_modules\\mapnik\\node_mo
dules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Tsvetik\AppData\Roaming\npm\node_modules\kosmtik\
node_modules\mapnik
node-pre-gyp ERR! node -v v8.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node
_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build
 --module=C:\Users\Tsvetik\AppData\Roaming\npm\node_modules\kosmtik\node_modules
\mapnik\lib\binding\mapnik.node --module_name=mapnik --module_path=C:\Users\Tsve
tik\AppData\Roaming\npm\node_modules\kosmtik\node_modules\mapnik\lib\binding' (1
)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapnik@3.7.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@3.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tsvetik\AppData\Roaming\npm-cache\_logs\2018-10-08T11_36_3
5_532Z-debug.log
```

**Comment by Danysan1** [comment]
This might be related to #212 (TLDR: Kosmtik only supports node.js v6  and lower).
If that's the case a solution could be this: https://ircama.github.io/osm-carto-tutorials/kosmtik-ubuntu-setup/#installation-procedure-suggested-by-openstreetmap-carto

**Comment by vinc** [comment]
I had the same problem with npm LTS 10.15.1, switched to LTS 6.16.0 (with asdf) and that fixed the issue, thanks!

The readme says:

> Note: Node.js versions are moving very fast, and kosmtik or its dependencies are hardly totally up to date with latest release. Ideally, you should run the LTS version of Node.js.

I guess the LTS version are also moving too fast! It'd be good to specify which LTS version is recommended in the readme.
