### ISSUE TITLE
Memory lack in tile server?

### ISSUE THREAD

**Issue by sommerluk** [kosmtik/kosmtik#298]
Hi.

When running Kosmtik in Ubuntu 19.04 installed on a physical machine, I get this error:

```
[httpserver] /openstreetmap-carto-with-data/tile/4/10/9.png?t=1555776759874 200
Trace
    at ProjectServer.raise (/home/sommerluk/Dokumente/OSM/kosmtik/src/back/ProjectServer.js:267:13)
    at /home/sommerluk/Dokumente/OSM/kosmtik/src/back/ProjectServer.js:85:34
    at /home/sommerluk/Dokumente/OSM/kosmtik/src/back/MetatileBasedTile.js:47:45
    at FSReqWrap.oncomplete (fs.js:141:20)
std::bad_alloc
```

Kosmtik is consuming extremly much memory. (I have 8 GB physical memory, and 11 GB swap.)

Correction: This seem to depend on the zoom level: The lower the zoom level of the tiles that are requested by the browser, the more memory is consumed. z3 and z4 are terrible, z15 works quite well.

**Comment by sommerluk** [comment]
Well, seems to be rather a [problem with `.index` files for shape files](https://github.com/gravitystorm/openstreetmap-carto/issues/2101#issuecomment-485286131) at these given low zoom levels. Problem disappears when deleting these `.index` files. So no problem of Kosmtik. Sorry for inconvenience. Closing.
