### ISSUE TITLE
Error installing master version with Docker

### ISSUE THREAD

**Issue by mrg218** [kosmtik/kosmtik#302]
I found a working Docker version of kosmtik 0.0.16 : https://hub.docker.com/r/joxit/kosmtik/dockerfile

But I want to have a working version of the master version (which uses a newer Mapnik version).

I do the following to install it:

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl ca-certificates gpg \
    && curl -sL https://deb.nodesource.com/setup_6.x | bash - \
    && apt-get install -y nodejs \
    && curl -sL https://github.com/kosmtik/kosmtik/archive/master.tar.gz | tar xz --strip-components=1 \
    && npm install --production \
    && node index.js plugins --install kosmtik-mbtiles-export

But the result is:

[Core] No usable config file found in /root/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Starting installation of kosmtik-mbtiles-export
/opt/kosmtik/node_modules/npm/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot convert undefined or null to object
    at /opt/kosmtik/src/back/PluginsManager.js:100:38
    at tryCatcher (/opt/kosmtik/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)

**Comment by yohanboniface** [comment]
plugins management through kosmtik is deprecated (the `npm` api totally disappeared), so for now one should install the normal way:

    npm install kosmtik-mbtiles-export

**Comment by Ircama** [comment]
> npm install kosmtik-mbtiles-export

This way the installation does not fail, but the plugins are not loaded. Example:

```
sudo npm install --unsafe-perm -g git+https://github.com/kosmtik/kosmtik
sudo npm install -g kosmtik-map-compare
kosmtik plugins --installed
```

Output:

```
[Core] No usable config file found in /home/ubuntu/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading plugin from ../plugins/version/index.js
Installed plugins
../plugins/base-exporters/index.js
../plugins/hash/index.js
../plugins/local-config/index.js
../plugins/datasource-loader/index.js
../plugins/version/index.js
```

*kosmtik-map-compare* is not loaded. How can this be fixed?

**Comment by yohanboniface** [comment]
Yes, that's an issue. Kosmtik used to have an internal command to install and register plugins, but `npm` is not more usable as a package.
This needs to be fixed in the kosmtik package, but I'm unsure how at this time.
In your case, you can register the plugins manually:

In the file `/home/ubuntu/.config/kosmtik.yml`, add:

```
plugins:
  - kosmtik-fetch-remote
  - kosmtik-map-compare
  - kosmtik-mbtiles-export
  …
```

And so on.

**Comment by Ircama** [comment]
@yohanboniface, thanks a lot!

This works with Ubuntu 20.04.2 LTS (for testing [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto)):

```shell
# Install nodejs:
sudo apt install -y nodejs npm

# Install kosmtik:
sudo npm install --unsafe-perm -g git+https://github.com/kosmtik/kosmtik

# Install kosmtik plugins:
sudo npm install -g kosmtik-overpass-layer
sudo npm install -g kosmtik-fetch-remote
sudo npm install -g kosmtik-overlay
sudo npm install -g kosmtik-map-compare
sudo npm install -g kosmtik-osm-data-overlay
sudo npm install -g kosmtik-tiles-export
sudo npm install -g kosmtik-magnacarto

# Plugins that might not work:
sudo npm install -g kosmtik-mapnik-reference
sudo npm install -g kosmtik-mbtiles-export
sudo npm install -g kosmtik-open-in-josm
sudo npm install -g kosmtik-geojson-overlay
sudo npm install -g kosmtik-place-search

# Activate plugins:
mkdir -p /home/$USER/.config
cat > /home/$USER/.config/kosmtik.yml <<\eof
plugins:
  # Plugins that should work:
  - kosmtik-fetch-remote
  - kosmtik-geojson-overlay
  - kosmtik-magnacarto
  - kosmtik-map-compare
  - kosmtik-overlay
  - kosmtik-overpass-layer
  - kosmtik-tiles-export
  # Plugins that might not work (commented out):
  #- kosmtik-mapnik-reference
  #- kosmtik-mbtiles-export
  #- kosmtik-open-in-josm
  #- kosmtik-osm-data-overlay
  #- kosmtik-place-search
eof

# Test installation:
kosmtik version
```

**Comment by JBacc1** [comment]
Thanks a lot. I guess this should find its place in the readme, or at least a link to it. I would never have managed without it.
