### ISSUE TITLE
kosmtik does not install on macos

### ISSUE THREAD

**Issue by denics** [kosmtik/kosmtik#325]
Dear all, I was using kosmtik some time ago and I was very happy. Unfortunately I had to reinstall my Mac, I moved to Catalina and now I cannot use kosmtik anymore. Here is the log:

```txt
/home/Git $ npm -g install kosmtik
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated protozero@1.5.1: protozero should no longer be used via npm, install instead via https://github.com/mapbox/mason
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/kosmtik -> /usr/local/lib/node_modules/kosmtik/index.js

> mapnik@3.7.2 install /usr/local/lib/node_modules/kosmtik/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v83-darwin-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@14.15.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v83-darwin-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@14.15.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
/bin/sh: mapnik-config: command not found
/bin/sh: mapnik-config: command not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! configure error
gyp ERR!gyp stack Error: `gyp` failed with exit code: 1
gyp ERR!  stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! ERR!stack      at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! gypstack      at ChildProcess.emit (events.js:315:20)
ERR!gyp  SystemERR! Darwin 19.6.0
 stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding"
gyp ERR! cwd /usr/local/lib/node_modules/kosmtik/node_modules/mapnik
gypgyp  ERR!ERR!  Systemnode -v Darwin 19.6.0
 v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp gypERR!  ERR!not ok
command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding"
gyp ERR! cwd /usr/local/lib/node_modules/kosmtik/node_modules/mapnik
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/kosmtik/node_modules/mapnik
node-pre-gyp ERR! node -v v14.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/usr/local/lib/node_modules/kosmtik/node_modules/mapnik/lib/binding' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapnik@3.7.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@3.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/denix/.npm/_logs/2020-11-06T08_10_12_078Z-debug.log
```

**Comment by sdacunha** [comment]
I used node v9 via nvm to fix this for now - might help you! I'm running Big Sur.

**Comment by tajchert** [comment]
Had same issue on MacOS Big Sur 11.2.2 with NPM 15.5.0, downgraded to[ 9.11.1](https://nodejs.org/en/blog/release/v9.11.1/) and was able to install kosmtik. Thanks for workaround @sdacunha

**Comment by gunyakov** [comment]
Ok. Looks like npm module wasn't update more than 4 years. Its mean that npm module have old dependencies. You have 2 choices to solve it. Or switch to node v.9.3.0 using nvm or clone this repository by git clone and after run command npm install.

**Comment by gy-mate** [comment]
@denics Have you tried running `npm -g install kosmtik` with the new instructions? It looks like this issue has been solved.

_cc @yohanboniface_
