### ISSUE TITLE
kosmtik export-tiles

### ISSUE THREAD

**Issue by pascal1162** [kosmtik/kosmtik#326]
Hi,
I did installed kosmtik on  localhost and tried to export tiles using the following command line :
(being in my installed kosmtik dir)
node index.js export ~/src/openstreetmap-carto/project.mml --format tiles --output /media/pascal/DATA/tiles --minZoom 10 --maxZoom 12

[Core] Loading config from /home/pascal/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading plugin from kosmtik-fetch-remote
[Core] Loading plugin from kosmtik-overlay
[Core] Loading plugin from kosmtik-open-in-josm
[Core] Loading plugin from kosmtik-map-compare
[Core] Loading plugin from kosmtik-osm-data-overlay
[Core] Loading plugin from kosmtik-mapnik-reference
[Core] Loading plugin from kosmtik-geojson-overlay
[Core] Loading plugin from kosmtik-tiles-export
[Core] Loading plugin from kosmtik-place-search
[Core] Loading project from /home/pascal/src/openstreetmap-carto/project.mml
[Core] Creating metatiles cache dir tmp/openstreetmap-carto/meta
[Core] Deleting previous metatiles tmp/openstreetmap-carto/meta
[Core] Created vector cache dir tmp/openstreetmap-carto/vector
[Local Config] Patched config from /home/pascal/src/openstreetmap-carto/localconfig.json
[Fetch Remote] Done.
/home/pascal/src/kosmtik/node_modules/kosmtik-tiles-export/Export.js:63
            delete next;
                   ^^^^

SyntaxError: Delete of an unqualified identifier in strict mode.
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Project.export (/home/pascal/src/kosmtik/src/back/Project.js:74:24)
    at Array.<anonymous> (/home/pascal/src/kosmtik/src/plugins/base-exporters/index.js:76:31)
    at Project.<anonymous> (/home/pascal/src/kosmtik/src/back/StateBase.js:23:47)
    at Project.<anonymous> (/home/pascal/src/kosmtik/src/back/StateBase.js:33:17)
    at done (/home/pascal/src/kosmtik/node_modules/kosmtik-fetch-remote/index.js:30:23)
    at decr (/home/pascal/src/kosmtik/node_modules/kosmtik-fetch-remote/index.js:25:17)
    at Project.FetchRemote.patchMML (/home/pascal/src/kosmtik/node_modules/kosmtik-fetch-remote/index.js:82:5)
    at Project.<anonymous> (/home/pascal/src/kosmtik/src/back/StateBase.js:31:78)
    at DataSourceLoader.patchMML (/home/pascal/src/kosmtik/src/plugins/datasource-loader/index.js:52:19)

What can be the problem ?

NB : When using ihm export button, choosing tiles as export format makes crash kosmtik ...

**Comment by yohanboniface** [comment]
Should be fixed since https://github.com/kosmtik/kosmtik-tiles-export/commit/d8841ce32e2fe57fc40cb520e792665bb1fb3332
