### ISSUE TITLE
kosmtik export tiles

### ISSUE THREAD

**Issue by lucadelu** [kosmtik/kosmtik#334]
If I try to export tiles from kosmtik with (kosmtik-tiles-export plugin) I get this error

```
/usr/local/lib/node_modules/kosmtik-tiles-export/Export.js:14
        this.ext = this.tileFormat.match(/^[a-z]*/);
                                   ^

TypeError: Cannot read property 'match' of undefined
    at TilesExporter.export (/usr/local/lib/node_modules/kosmtik-tiles-export/Export.js:14:36)
    at Project.export (/usr/local/lib/node_modules/kosmtik/src/back/Project.js:76:24)
    at ProjectServer.export (/usr/local/lib/node_modules/kosmtik/src/back/ProjectServer.js:241:28)
    at ProjectServer.serve (/usr/local/lib/node_modules/kosmtik/src/back/ProjectServer.js:47:53)
    at PreviewServer.forwardToProject (/usr/local/lib/node_modules/kosmtik/src/back/PreviewServer.js:72:27)
    at PreviewServer.serve (/usr/local/lib/node_modules/kosmtik/src/back/PreviewServer.js:66:46)
    at Server.emit (events.js:314:20)
    at parserOnIncoming (_http_server.js:779:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
```

**Comment by yohanboniface** [comment]
Strange! Can you share the exact command you've run ?

**Comment by lucadelu** [comment]
I run it for the web-client, I didn't see that I have to run it from command line. From command line it work properly
