### ISSUE TITLE
Problem with Installation 

### ISSUE THREAD

**Issue by safen** [kosmtik/kosmtik#343]
Hello I'm trying to install it but I get this errors 

```
npm WARN deprecated protozero@1.5.1: protozero should no longer be used via npm, install instead via https://github.com/mapbox/mason

> mapnik@3.7.2 install /home/administrator/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v72-linux-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@12.22.12 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v72-linux-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@12.22.12 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
gyp WARN EACCES current user ("administrator") does not have permission to access the dev dir "/root/.cache/node-gyp/12.22.12"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/administrator/node_modules/mapnik/.node-gyp"
gyp WARN EACCES current user ("administrator") does not have permission to access the dev dir "/root/.cache/node-gyp/12.22.12"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/administrator/node_modules/mapnik/.node-gyp"
make: Entering directory '/home/administrator/node_modules/mapnik/build'
make: *** No rule to make target '../.node-gyp/12.22.12/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/administrator/node_modules/mapnik/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.0-124-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/administrator/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/home/administrator/node_modules/mapnik/lib/binding"
gyp ERR! cwd /home/administrator/node_modules/mapnik
gyp ERR! node -v v12.22.12
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/administrator/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/home/administrator/node_modules/mapnik/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/administrator/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 5.4.0-124-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/administrator/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/administrator/node_modules/mapnik
node-pre-gyp ERR! node -v v12.22.12
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/administrator/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/home/administrator/node_modules/mapnik/lib/binding' (1)
make: Entering directory '/home/administrator/node_modules/mapnik/build'
make: *** No rule to make target '../.node-gyp/12.22.12/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/administrator/node_modules/mapnik/bui
    
```

**Comment by davide84** [comment]
See https://github.com/kosmtik/kosmtik/issues/335#issuecomment-1112518345 it solved for me (downloaded the git repo and then run 'npm install').

**Comment by safen** [comment]
> See [#335 (comment)](https://github.com/kosmtik/kosmtik/issues/335#issuecomment-1112518345) it solved for me (downloaded the git repo and then run 'npm install').

thank you
