### ISSUE TITLE
TileJSON needed on XML conversion

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#55]
I'm converting a style (vector tile -> raster) to Mapnik XML. At time of conversion, the TileJSON for the vector tiles does not exist and Kosmtik gives the error
```
[Core] Using mapnik version 3.0.0
/data/servers/mq_nms/kosmtik/src/plugins/datasource-loader/index.js:20
                if (err) throw err;
                               ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
```
I was wondering

1. Is it necessary to have the TileJSON at time of conversion for some of the content of the XML?

2. If it is, would any problems be caused by using a dummy one?

**Comment by pnorman** [comment]
Looking at the source, all that's used from the tilejson is the URL of the first tile source (e.g. "http://a.tile.source/${z}/${x}/${y}.pbf").

Given this, what I did was wrote a dummy tilejson with

```sh
cat > tile.json <<EOF
{
  "tiles":[
    "http://localhost:8080/${z}/${x}/${y}.pbf"
  ]
}
EOF
```
and substituted it with [`./change_vector_source.sh "file://${PWD}/tile.json"`](https://github.com/MapQuest/mq-carto-style-vector/blob/master/change_vector_source.sh)

**Comment by yohanboniface** [comment]
> Looking at the source, all that's used from the tilejson is the URL of the first tile source (e.g. "http://a.tile.source/${z}/${x}/${y}.pbf").

Watch out that this may change in the future, as I'd like to deduce the layers from the tilejson in case they are not defined in the style mml.

One suggestion: you can change your source to something like `tms://a.tile.source/{z}/{x}/{y}.pbf` so that no tilejson request will be made, as we consider that this `tms` is the final tile URL to be used as data source (yeah, I know, I need to start working on a documentation! ;) ).

**Comment by pnorman** [comment]
> Watch out that this may change in the future, as I'd like to deduce the layers from the tilejson in case they are not defined in the style mml.

Thinking about it, I suppose the sensible thing to do in my situation is to point at the tm2source, since I'm handling it in the same jenkins build.
