### ISSUE TITLE
Wrong filename given with localconfig json error

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#60]
I had an error in my localconfig.json and got the error

```
undefined:11
]
^
SyntaxError: Unexpected token ]
    at Object.parse (native)
    at L.fromString (/usr/home/pnorman/osm/kosmtik/node_modules/json-localizer/index.js:71:46)
    at /usr/home/pnorman/osm/kosmtik/src/plugins/local-config/index.js:38:15
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
```

Instead of being told the filename, it is "undefined".

**Comment by yohanboniface** [comment]
Fixed, thanks for the report :)
