### ISSUE TITLE
Node 0.12.x

### ISSUE THREAD

**Issue by jczaplew** [kosmtik/kosmtik#73]
It seems that there are some issues using anything > `0.10.36`, but I haven't had a chance to figure out where the errors might be coming from. Are there any plans to ensure compatibility with more recent versions of Node? If so, where would be a good place to start working on this fix?

Thanks! I've really been enjoying kosmtik!

**Comment by yohanboniface** [comment]
```
node --version
v0.12.7
```
I'm using Node 0.12 myself, so it must be something else. Are you sure you are up to date with Kosmtik codebase? Do you have any stack trace to start investigating?

**Comment by jczaplew** [comment]
I just had an issue where I was using `0.12.5`, an error was thrown while exporting to Mapnik XML, I switched to `0.10.36` and it worked, but now I can't replicate it! I'll use 0.12.7 from now on and see if it happens again. 

This is the error I saw when it did happen though:

````
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/jczaplewski/burwell/tiles/node_modules/kosmtik/node_modules/mapnik/lib/binding/node-v14-darwin-x64/mapnik_settings.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jczaplewski/burwell/tiles/node_modules/kosmtik/node_modules/mapnik/lib/mapnik.js:8:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
````

**Comment by yohanboniface** [comment]
Weird. Let's keep an eye open.
