### ISSUE TITLE
Serving world example with mapnik 3.0.1 fails

### ISSUE THREAD

**Issue by cmyk** [kosmtik/kosmtik#78]
It doesn't seem to work.
Not sure if it's a problem with mapnik 3.0.1?
This is on Debian 8.

```
osm@map:~/carto/kosmtik$ node index.js  serve --host map.example.com test/data/world/project.yml 
[Core] No usable config file found in /home/osm/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading project from test/data/world/project.yml
[Core] PreviewServer started, you can browse http://map.example.com:6789
[Local Config] Unable to load local config from /home/osm/carto/kosmtik/test/data/world/localconfig.js
[Error: File not found: /home/osm/carto/kosmtik/test/data/world/localconfig.js]
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.0.1
Unknown mapnik-reference version: '3.0.1'
[httpserver] /data/poll/ 404
[httpserver] /data/poll/ 404
[httpserver] /data/poll/ 404
[httpserver] /data/ 404
[httpserver] / 302
[httpserver] /world 302
[httpserver] / 302
[httpserver] /world 302
[httpserver] /world/ 200
[httpserver] /world/config/ 200
[httpserver] /node_modules/leaflet-formbuilder/Leaflet.FormBuilder.js 200
[httpserver] /src/front/Core.js 200
[httpserver] /node_modules/leaflet/dist/leaflet.css 200
[httpserver] /config/ 200
[httpserver] /src/front/Autocomplete.js 200
[httpserver] /node_modules/leaflet/dist/leaflet-src.js 200
[httpserver] /src/front/Sidebar.css 200
[httpserver] /src/front/Toolbar.css 200
[httpserver] /src/front/Core.css 200
[httpserver] /src/front/DataInspector.js 200
[httpserver] /src/front/MetatilesBounds.js 200
[httpserver] /src/front/Sidebar.js 200
[httpserver] /src/front/Toolbar.js 200
[httpserver] /src/front/FormBuilder.js 200
[httpserver] /src/front/Settings.js 200
[httpserver] /src/front/Command.js 200
[httpserver] /src/front/Map.js 200
[httpserver] /src/plugins/base-exporters/front/export.js 200
[httpserver] /node_modules/leaflet-hash/leaflet-hash.js 200
[httpserver] /hash.js 200
[httpserver] /src/front/header_logo.svg 200
Trace
    at ProjectServer.raise (/home/osm/carto/kosmtik/src/back/ProjectServer.js:239:13)
    at ProjectServer.serveTile (/home/osm/carto/kosmtik/src/back/ProjectServer.js:61:14)
    at tile (/home/osm/carto/kosmtik/src/back/ProjectServer.js:44:108)
    at StateBase.when (/home/osm/carto/kosmtik/src/back/StateBase.js:51:33)
    at ProjectServer.serve (/home/osm/carto/kosmtik/src/back/ProjectServer.js:44:70)
    at PreviewServer.forwardToProject (/home/osm/carto/kosmtik/src/back/PreviewServer.js:74:23)
    at PreviewServer.serve (/home/osm/carto/kosmtik/src/back/PreviewServer.js:68:42)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
Project not loaded properly.
[httpserver] /world/tile/0/0/0.png?t=1438675826126 500
[httpserver] /src/front/fonts/FiraSans-Light.woff 200
[httpserver] /src/front/fonts/DejaVuSans-webfont.woff 200
[httpserver] /world/poll/ 200
```

**Comment by yohanboniface** [comment]
pass `--mapnik-version 3.0.0` argument to the `serve` command for now.

I'll see how to handle that properly :)

**Comment by cmyk** [comment]
Wow, you're quick!
Yep, that does the trick. World is showing up now.
