### ISSUE TITLE
Error when vector tile source returns 404

### ISSUE THREAD

**Issue by jbrwn** [kosmtik/kosmtik#83]
kosmtik is throwing a hard error when a vector tile source returns a 404.   

```
Joels-MacBook-Pro:kosmtik joelbrown$ node index.js serve ../tilemill/test2.tm2/project.yml
[Core] No usable config file found in /Users/joelbrown/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading project from ../tilemill/test2.tm2/project.yml
[Core] PreviewServer started, you can browse http://127.0.0.1:6789
[Local Config] Unable to load local config from /Users/joelbrown/tilemill/test2.tm2/localconfig.js
[Error: File not found: /Users/joelbrown/tilemill/test2.tm2/localconfig.js]
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.0.0
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
[httpserver] /test2.tm2/tile/1/0/0.png?t=1438983099059 200
[httpserver] /test2.tm2/tile/1/1/0.png?t=1438983099059 200
[httpserver] /test2.tm2/tile/1/0/1.png?t=1438983099059 200
[httpserver] /test2.tm2/tile/1/1/1.png?t=1438983099059 200
[httpserver] /test2.tm2/tile/2/1/1.png?t=1438983099059 200
[httpserver] /test2.tm2/tile/2/2/1.png?t=1438983099059 200
[httpserver] /test2.tm2/tile/2/2/0.png?t=1438983099059 200
[httpserver] /test2.tm2/tile/2/2/2.png?t=1438983099059 200
[httpserver] /test2.tm2/tile/2/1/2.png?t=1438983099059 200
could not parse buffer as protobuf
Trace
    at ProjectServer.raise (/Users/joelbrown/kosmtik/src/back/ProjectServer.js:239:13)
    at /Users/joelbrown/kosmtik/src/back/ProjectServer.js:73:34
    at /Users/joelbrown/kosmtik/src/back/VectorBasedTile.js:61:18
    at parse (/Users/joelbrown/kosmtik/src/back/VectorBasedTile.js:24:17)
    at Request.onResponse [as _callback] (/Users/joelbrown/kosmtik/src/back/VectorBasedTile.js:41:17)
    at Request.self.callback (/Users/joelbrown/kosmtik/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/joelbrown/kosmtik/node_modules/request/request.js:1057:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/joelbrown/kosmtik/node_modules/request/request.js:1003:12)
Unable to parse vector tile data for uri http://a.tiles.mapbox.com/v3/joelsbrown1.ffb527f1/2/1/0.vector.pbf
[httpserver] /test2.tm2/tile/2/1/0.png?t=1438983099059 500
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at /Users/joelbrown/kosmtik/src/back/ProjectServer.js:77:21
```

```http://a.tiles.mapbox.com/v3/joelsbrown1.ffb527f1/2/1/0.vector.pbf``` returns a 404.  What is the expected behavior here?  My expectation is that a "empty" tile should be rendered.  At the very least i would not expect this to break the app.   Let me know what you think.

**Comment by yohanboniface** [comment]
You're absolutely right :)
Now it raise an internal error, which then got displayed to the user.
