### ISSUE TITLE
Crash when XRay tile tries to render with no data 

### ISSUE THREAD

**Issue by timwaters** [kosmtik/kosmtik#94]
Seems like #51 has reared it's head again.

```
When viewing a tile with no data, the Xray tile errors. 

/home/tim/projects/kosmtik/src/back/XRayTile.js:19
    vtile.parse();
          ^
Error: cannot parse 0 length buffer as protobuf
    at XRayTile.render (/home/tim/projects/kosmtik/src/back/XRayTile.js:19:11)
    at /home/tim/projects/kosmtik/src/back/ProjectServer.js:139:19
```
as before, similar patch will get it working
```
if (this.data.length) vtile.parse();
```

Will make a pull request for it.

**Comment by yohanboniface** [comment]
Fixed by #95
